"""Regression tests: Berlekamp-Massey algorithm + LFSR helpers.

Covers:
1. BM on known short LFSR sequences (verifiable by hand)
2. `recover_lfsr` recovers the correct polynomial from output values
3. `compute_checksum` produces identical results to `zlib.crc32` for the
   standard polynomial
4. `linear_complexity` increases with sequence length
5. `recover_polynomial_gcd` recovers the standard CRC-32 polynomial from
   enough independent (data, checksum) pairs
6. End-to-end: recover a custom non-standard polynomial, then compute
   valid checksums with it
"""

from __future__ import annotations

import struct
import zlib

from fuzzer_tool.core.berlekamp_massey import (
    _reverse_bits,
    _reverse_byte,
    berlekamp_massey,
    compute_checksum,
    lfsr_step,
    linear_complexity,
    recover_lfsr,
    recover_polynomial_gcd,
    sequence_linear_complexity,
)

# ---------------------------------------------------------------------------
# Known LFSR sequences (from textbook examples)
# ---------------------------------------------------------------------------

# LFSR with connection polynomial x^3 + x + 1 (poly = 0b1011 reversed = 0b1101 = 13)
# Seed = 0b001, output the shifted-out bit each step
_POLY_3BIT = 0b1011  # standard form: x^3 + x + 1
# reversed form for lfsr_step = bit-reversed: bit 0→0, bit1→1, bit2→1, bit3→1 = 0b1110 = 14
_POLY_3BIT_REV = 0b1110


def _lfsr3(seed: int, n: int) -> list[int]:
    """Generate n output bits from a 3-bit LFSR (poly = x^3 + x + 1)."""
    state = seed & 0b111
    out = []
    for _ in range(n):
        out.append(state & 1)
        feedback = (state & 1) ^ ((state >> 1) & 1)  # taps at bits 0 and 1
        state = ((state >> 1) | (feedback << 2)) & 0b111
    return out


def test_bm_recovers_3bit_lfsr():
    """BM finds L=3 for a sequence generated by a 3-bit LFSR."""
    bits = _lfsr3(0b001, 20)
    L, C = berlekamp_massey(bits)
    assert L == 3
    # C[0]=1, C[1]=1 (tap at x^1), C[2]=0, C[3]=1 (tap at x^3)
    assert C[0] == 1
    assert C[3] == 1


def test_bm_linear_complexity_flat_sequence():
    """All-zeros sequence has L=0."""
    L, _ = berlekamp_massey([0] * 50)
    assert L == 0


def test_bm_linear_complexity_alternating():
    """Alternating 010101... has L=2 (recurrence s[n] = s[n-2])."""
    L, C = berlekamp_massey([i % 2 for i in range(100)])
    assert L == 2
    assert C == [1, 0, 1]  # x^2 + 1


# ---------------------------------------------------------------------------
# `recover_lfsr`
# ---------------------------------------------------------------------------


def test_recover_lfsr_sequential_states():
    """recover_lfsr recovers the poly from sequential LFSR states.

    Values must be raw register states one step apart (``lfsr_step``
    output); ``zlib.crc32`` of different messages is *not* such a
    sequence (independent inputs, init/final_xor applied).
    """
    poly = 0xEDB88320
    state = 0xDEADBEEF
    values = [state]
    for _ in range(64):
        state = lfsr_step(state, poly, 32)
        values.append(state)
    assert recover_lfsr(values, width=32) == poly


def test_recover_lfsr_crc32c():
    """recover_lfsr also handles a different reflected poly (CRC-32C)."""
    poly = 0x1DB71064
    state = 0x12345678
    values = [state]
    for _ in range(64):
        state = lfsr_step(state, poly, 32)
        values.append(state)
    assert recover_lfsr(values, width=32) == poly


def test_recover_lfsr_too_few_values():
    """With fewer than 2 values, recovery returns None."""
    assert recover_lfsr([], width=32) is None
    assert recover_lfsr([42], width=32) is None


# ---------------------------------------------------------------------------
# `compute_checksum` vs `zlib.crc32`
# ---------------------------------------------------------------------------


def test_compute_checksum_matches_zlib():
    """With the full zlib.crc32 configuration, compute_checksum matches it.

    zlib.crc32 is reflected with init/final_xor 0xFFFFFFFF; the GCD-domain
    defaults (init=0, final_xor=0, non-reflected) intentionally differ.
    """
    for data in [b"", b"hello", b"\x00" * 64, bytes(range(256))]:
        got = compute_checksum(
            data,
            poly=0xEDB88320,
            width=32,
            init=0xFFFFFFFF,
            final_xor=0xFFFFFFFF,
            reflect_in=True,
            reflect_out=False,
        )
        expected = zlib.crc32(data) & 0xFFFFFFFF
        assert got == expected, f"mismatch for {data[:8]!r}: {got} != {expected}"


def test_compute_checksum_custom_poly_differs():
    """A non-standard polynomial produces different results."""
    STANDARD = 0xEDB88320
    # Poly 0x1D (x^8 + x^4 + x^3 + x^2 + 1 — simple 8-bit example)
    custom = 0x1D
    data = b"hello world"
    std = compute_checksum(data, poly=STANDARD, width=32)
    cus = compute_checksum(data, poly=custom, width=32)
    assert std != cus


# ---------------------------------------------------------------------------
# `recover_polynomial_gcd`
# ---------------------------------------------------------------------------


def test_gcd_recovers_standard_poly():
    """GCD-of-syndromes recovers the standard CRC-32 polynomial.

    Pairs must live in the GCD domain (non-reflected, init=0,
    final_xor=0) — raw ``zlib.crc32`` outputs (reflected, init/final_xor
    0xFFFFFFFF) are not in that domain.  The recovered generator is the
    normal form 0x04C11DB7 (the bit-reversal of 0xEDB88320); the GCD may
    carry extra factors, so the round-trip is the authoritative check.
    """
    pairs = []
    for i in range(64):
        data = bytes([i])
        crc = compute_checksum(data, poly=0x04C11DB7, width=32)
        pairs.append((data, crc))

    poly = recover_polynomial_gcd(pairs, width=32)
    assert poly is not None
    # Strip trailing zeros (normalize) — the GCD is a multiple of the generator.
    while poly and not (poly & 1):
        poly >>= 1
    assert (poly & 0xFFFFFFFF) == 0x04C11DB7
    # Round-trip: the recovered poly reproduces every observed checksum.
    for data, crc in pairs:
        assert compute_checksum(data, poly=poly, width=32) == crc


def test_reverse_bits_helpers():
    """_reverse_bits/_reverse_byte are self-inverse and match known values."""
    assert _reverse_byte(0b10110000) == 0b00001101
    assert _reverse_byte(0) == 0
    assert _reverse_byte(0xFF) == 0xFF
    assert _reverse_bits(0xEDB88320, 32) == 0x04C11DB7  # standard <-> normal CRC-32 forms
    for x in (0, 1, 0x12345678, 0xFFFFFFFF):
        assert _reverse_bits(_reverse_bits(x, 32), 32) == x


def test_gcd_too_few_pairs():
    """With < 2 pairs, returns None."""
    assert recover_polynomial_gcd([], width=32) is None
    assert recover_polynomial_gcd([(b"x", 1)], width=32) is None


def test_gcd_recovers_standard_poly_reflected():
    """GCD-of-syndromes recovers the standard (real-world) reflected
    CRC-32 polynomial from independent pairs — the common case that the
    non-reflected-only path can't handle, since virtually every
    real-world CRC-32 (zlib, gzip, PNG, ZIP, Ethernet) is reflected.
    """
    STANDARD_POLY = 0xEDB88320
    pairs = []
    for i in range(64):
        data = bytes([i, (i * 7) & 0xFF, (i * 13) & 0xFF])
        crc = compute_checksum(data, poly=STANDARD_POLY, width=32, reflect_in=True)
        pairs.append((data, crc))

    poly = recover_polynomial_gcd(pairs, width=32, reflected=True)
    assert poly == STANDARD_POLY
    for data, crc in pairs:
        assert compute_checksum(data, poly=poly, width=32, reflect_in=True) == crc


def test_gcd_recovers_custom_poly_reflected():
    """Recovers a genuinely different, non-standard real-world polynomial
    (CRC-32C / Castagnoli) — proves this isn't coincidentally matching a
    hardcoded standard-CRC32 fallback somewhere.
    """
    CRC32C_POLY = 0x82F63B78
    pairs = []
    for i in range(64):
        data = bytes([i, (i * 3 + 1) & 0xFF])
        crc = compute_checksum(data, poly=CRC32C_POLY, width=32, reflect_in=True)
        pairs.append((data, crc))

    poly = recover_polynomial_gcd(pairs, width=32, reflected=True)
    assert poly == CRC32C_POLY
    for data, crc in pairs:
        assert compute_checksum(data, poly=poly, width=32, reflect_in=True) == crc


def test_gcd_result_masked_to_width():
    """The recovered polynomial is masked to `width` bits — the
    conventional truncated representation (0xEDB88320), not the raw GCD
    result with an extra explicit leading bit (0x1EDB88320).
    """
    pairs = []
    for i in range(64):
        data = bytes([i])
        crc = compute_checksum(data, poly=0x04C11DB7, width=32)
        pairs.append((data, crc))

    poly = recover_polynomial_gcd(pairs, width=32)
    assert poly is not None
    assert poly <= 0xFFFFFFFF, f"result should be masked to 32 bits, got {hex(poly)}"


def test_checksum_learner_recovers_reflected_from_independent_pairs():
    """End-to-end: ChecksumLearner recovers a real-world-style reflected
    CRC-32 (init=0, final_xor=0 domain — the domain _recover() targets)
    from independent (data, checksum) pairs sourced from different
    random buffers, the way a real fuzzing corpus would produce them.
    This is the scenario the reflected-GCD fix directly addresses.
    """
    import random

    from fuzzer_tool.core.checksum_learner import ChecksumLearner

    class _FakeFuzzer:
        pass

    STANDARD_POLY = 0xEDB88320
    rng = random.Random(5)
    learner = ChecksumLearner(_FakeFuzzer(), min_pairs=64)

    pairs = []
    for _ in range(80):
        n = rng.randint(4, 40)
        data = bytes(rng.randint(0, 255) for _ in range(n))
        crc = compute_checksum(data, poly=STANDARD_POLY, width=32, reflect_in=True)
        pairs.append((data, crc))
    learner.add_pairs(pairs)

    poly = learner.ensure_poly()
    assert poly == STANDARD_POLY
    assert learner._reflect is True

    # Predict on genuinely unseen data.
    for _ in range(50):
        n = rng.randint(4, 40)
        data = bytes(rng.randint(0, 255) for _ in range(n))
        true_crc = compute_checksum(data, poly=STANDARD_POLY, width=32, reflect_in=True)
        assert learner.compute_checksum(data) == true_crc


# ---------------------------------------------------------------------------
# `linear_complexity` structuredness metric
# ---------------------------------------------------------------------------


def test_linear_complexity_random_high():
    """Random bytes should have high linear complexity."""
    import secrets

    data = secrets.token_bytes(256)
    lc = sequence_linear_complexity(data)
    # For random data, BM typically recovers L ≈ sequence length (no short LFSR)
    assert lc > 200  # generous lower bound


def test_linear_complexity_structured_low():
    """Data generated by a short LFSR has low linear complexity."""
    # Generate 64 bits from a 3-bit LFSR
    bits = _lfsr3(0b001, 64)
    lc = linear_complexity(bits)
    assert lc == 3


# ---------------------------------------------------------------------------
# CRC32 wrapper
# ---------------------------------------------------------------------------


def test_crc32_wrapper_standard():
    """The crc32 wrapper matches zlib.crc32 with no active poly."""
    from fuzzer_tool.core.crc32 import crc32

    for data in [b"", b"test", bytes(range(16))]:
        assert crc32(data) == zlib.crc32(data) & 0xFFFFFFFF


def test_crc32_wrapper_uses_active_poly():
    """When an active poly is set, crc32 uses it."""
    from fuzzer_tool.core.crc32 import crc32, set_active_poly

    custom = 0x1D  # different from standard
    set_active_poly(custom)
    try:
        data = b"hello"
        assert crc32(data) != zlib.crc32(data) & 0xFFFFFFFF
    finally:
        set_active_poly(None)


def test_crc32_wrapper_reset():
    """After reset, crc32 falls back to standard."""
    from fuzzer_tool.core.crc32 import crc32, set_active_poly

    set_active_poly(0x1D)
    set_active_poly(None)
    assert crc32(b"test") == zlib.crc32(b"test") & 0xFFFFFFFF


# ---------------------------------------------------------------------------
# PNG pair extraction
# ---------------------------------------------------------------------------


def test_extract_png_pairs():
    """Format-aware extractor pulls (type+data, crc) from a real PNG."""
    from fuzzer_tool.core.checksum_learner import ChecksumLearner

    # Minimal valid PNG: signature + IHDR chunk + IEND chunk
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr_data = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)
    ihdr_type = b"IHDR"
    ihdr_crc_val = zlib.crc32(ihdr_type + ihdr_data) & 0xFFFFFFFF
    ihdr_chunk = (
        struct.pack(">I", len(ihdr_data)) + ihdr_type + ihdr_data + struct.pack(">I", ihdr_crc_val)
    )
    iend_chunk = (
        struct.pack(">I", 0) + b"IEND" + struct.pack(">I", zlib.crc32(b"IEND") & 0xFFFFFFFF)
    )
    png = sig + ihdr_chunk + iend_chunk

    # Use a fake fuzzer with checksum_learner=None
    class FakeFuzzer:
        checksum_learner = None

    learner = ChecksumLearner(FakeFuzzer())
    pairs = learner.extract_format_pairs(png)
    assert len(pairs) >= 2
    for data, _crc in pairs:
        assert len(data) > 0
        assert len(data) == len(b"IHDR" + ihdr_data) or len(data) == len(b"IEND")


# ---------------------------------------------------------------------------
# End-to-end: recover a custom polynomial and compute valid checksums
# ---------------------------------------------------------------------------


def test_end_to_end_custom_poly():
    """Recover a custom poly from pairs, then compute valid checksums."""
    from fuzzer_tool.core.berlekamp_massey import recover_polynomial_gcd

    # Use a simple custom poly: x^8 + x^4 + x^3 + x^2 + 1 (reversed = 0x1D)
    # We manually compute the checksum so we know the exact poly.
    CUSTOM_POLY = 0x1D  # reversed form for width=8
    pairs = []
    for i in range(64):
        data = bytes([i])
        expected = compute_checksum(data, poly=CUSTOM_POLY, width=8)
        pairs.append((data, expected))

    poly = recover_polynomial_gcd(pairs, width=8)
    assert poly is not None
    # Normalize: strip trailing zeros
    norm = poly
    while norm and not (norm & 1):
        norm >>= 1
    # The GCD should be a multiple of the generator; the normalized form
    # may differ by a factor (x) if the poly has a zero coefficient.
    # Verify by round-trip: poly found should reproduce all checksums.
    for data, expected in pairs:
        got = compute_checksum(data, poly=norm, width=8)
        assert got == expected, f"round-trip failed for {data!r}: {got} != {expected}"


# ---------------------------------------------------------------------------
# Operator registration
# ---------------------------------------------------------------------------


def test_crc_learn_registered_in_registry():
    """crc_learn is registered in the adaptive band."""
    from fuzzer_tool.core.operator_categories import OPERATOR_CATEGORIES

    assert "crc_learn" in OPERATOR_CATEGORIES.get("adaptive", set())


def test_crc_learn_availability_no_fuzzer():
    """crc_learn is unavailable when passed None fuzzer."""
    from fuzzer_tool.core.operator_registry import REGISTRY

    assert "crc_learn" not in REGISTRY.available(None, b"")
