"""Tests for core/lcg_recovery.py: truncated-output LCG state recovery via LLL (P4-1).

Streams are generated by a reference LCG written here, independent of the
module's own step/output functions.
"""

import pytest

from fuzzer_tool.core.lcg_recovery import (
    LCG_FAMILIES,
    LCGSpec,
    confident_samples,
    lcg_family,
    min_samples,
    predict_words,
    recover_state,
    verify_state,
    walk_stream,
)
from fuzzer_tool.core.rand_pool import RandPool

JAVA = LCG_FAMILIES["java"]
MSVC = LCG_FAMILIES["msvc"]


def _ref_stream(x: int, n: int, a: int, c: int, m: int, shift: int, out_bits: int) -> list[int]:
    """Reference generator: output (x >> shift) & mask, then x = a*x + c mod m."""
    out = []
    for _ in range(n):
        out.append((x >> shift) & ((1 << out_bits) - 1))
        x = (a * x + c) % m
    return out


def _stream(spec: LCGSpec, x: int, n: int) -> list[int]:
    return _ref_stream(x, n, spec.a, spec.c, spec.m, spec.shift, spec.out_bits)


class TestSpec:
    def test_power_of_two_modulus_is_truncated_to_observed_bits(self):
        """Bits above shift+out_bits never reach lower bits of an LCG mod 2^k."""
        assert MSVC.modulus == 1 << (MSVC.shift + MSVC.out_bits)
        assert JAVA.modulus == JAVA.m

    def test_unobservable_top_bits_rejected(self):
        """Adversarial: a non-power-of-two modulus wider than the output window is unrecoverable."""
        with pytest.raises(ValueError):
            LCGSpec("bad", a=3, c=1, m=(1 << 40) - 87, shift=0, out_bits=16)

    def test_sample_counts(self):
        for spec in LCG_FAMILIES.values():
            assert confident_samples(spec) == min_samples(spec) + 1
            assert min_samples(spec) * spec.out_bits > spec.state_bits

    def test_lookup(self):
        assert lcg_family("java") is JAVA
        assert lcg_family("nope") is None


class TestRecovery:
    @pytest.mark.parametrize("name", sorted(LCG_FAMILIES))
    def test_recovers_and_predicts(self, name):
        spec = LCG_FAMILIES[name]
        rng = RandPool(seed=11)
        n = confident_samples(spec)
        for _ in range(20):
            x0 = rng.randrange(spec.m)
            ys = _stream(spec, x0, n + 6)
            state = recover_state(ys[:n], spec)
            assert state is not None
            assert verify_state(state, ys[:n], spec)
            # Falsification: predictions must match the reference beyond the samples.
            assert predict_words(state, n + 5, spec) == ys[1 : n + 6]

    def test_state_is_origin_aligned(self):
        x0 = 0x1234_5678_9ABC
        ys = _stream(JAVA, x0, 4)
        assert recover_state(ys, JAVA) == (x0,)

    def test_too_few_samples_raise(self):
        with pytest.raises(ValueError):
            recover_state([1], JAVA)

    def test_out_of_range_word_rejected(self):
        """Adversarial: a 15-bit family cannot emit a 16-bit word."""
        ys = _stream(MSVC, 99, 5)
        ys[2] = 1 << MSVC.out_bits
        assert recover_state(ys, MSVC) is None

    def test_random_words_do_not_verify(self):
        """Adversarial: unrelated constants must not fit at the confident count."""
        rng = RandPool(seed=5)
        n = confident_samples(JAVA)
        hits = sum(
            recover_state([rng.randrange(1 << 32) for _ in range(n)], JAVA) is not None
            for _ in range(50)
        )
        assert hits == 0

    def test_control_self_consistent(self):
        """Control (Rule 46): recovery on the same stream twice returns the same state."""
        ys = _stream(MSVC, 424242, 6)
        assert recover_state(ys, MSVC) == recover_state(ys, MSVC)


class TestWalk:
    def test_walk_matches_reference(self):
        x0 = 777
        ys = _stream(JAVA, x0, 4)
        assert [w for _, w in walk_stream((x0,), 3, JAVA)] == ys[1:]
