"""Regression test: quoted grammar literals decode escapes, and the shipped
.gram files generate their declared magic bytes.

Two defects, both silent, both in the same class as the parse_dict_line
enclosing-quote bug -- well-typed output, wrong bytes:

1. Quoted literals kept their backslash text VERBATIM, so ``"\\xFF\\xD8"``
   was eight ASCII characters rather than the two-byte JPEG SOI marker.
   All 35 rules of ``dictionaries/jpeg.gram`` are quoted marker definitions,
   so the entire grammar emitted literal ``\\xFF\\xD8`` text and could never
   produce a JPEG.

2. An undefined rule reference expands to ``b"?"`` and logged at DEBUG, so
   it was invisible. ``png.gram`` shipped with five (PNG, IHDR, IDAT, IEND,
   PLTE -- bare words are rule references, and these were meant as literal
   chunk names) and ``rar.gram`` with two, one of which (``header_chain``)
   was referenced by the START rule and never defined at all. Every PNG
   generation carried ~8 stray '?' bytes and no valid chunk name.

The first defect was pinned in place by a test asserting the buggy value.
The assertions here are on generated bytes, so a regression shows up as a
wrong magic number rather than a passing type check.
"""

from __future__ import annotations

import logging
import os

import pytest

from fuzzer_tool.core.grammar import Grammar, decode_quoted_literal, load_grammar

_DICT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "dictionaries"
)


class TestQuotedLiteralEscapes:
    def test_hex_escape_uppercase(self):
        assert decode_quoted_literal(r"\xFF\xD8") == b"\xff\xd8"

    def test_hex_escape_lowercase(self):
        assert decode_quoted_literal(r"\x89\x0a") == b"\x89\n"

    def test_simple_escapes(self):
        assert decode_quoted_literal(r"a\tb\rc\nd\0e") == b"a\tb\rc\nd\x00e"

    def test_escaped_backslash_is_not_a_hex_escape(self):
        r"""\\x41 is backslash + "x41", not backslash + "A"."""
        assert decode_quoted_literal(r"\\x41") == b"\\x41"

    def test_escaped_quote(self):
        assert decode_quoted_literal(r"a\"b") == b'a"b'

    def test_unknown_escape_keeps_its_backslash(self):
        assert decode_quoted_literal(r"\q") == b"\\q"

    def test_trailing_lone_backslash(self):
        assert decode_quoted_literal("ab\\") == b"ab\\"

    def test_short_hex_escape_is_not_consumed(self):
        assert decode_quoted_literal(r"\x4") == b"\\x4"

    def test_plain_text_untouched(self):
        assert decode_quoted_literal("IHDR") == b"IHDR"


class TestGrammarIntegration:
    def test_quoted_binary_literal_generates_those_bytes(self):
        g = Grammar()
        g.parse(r'soi = "\xFF\xD8"')
        assert g.generate("soi") == b"\xff\xd8"

    def test_quoted_and_unquoted_escapes_agree(self):
        a, b = Grammar(), Grammar()
        a.parse(r'data = "\x30\x31"')
        b.parse(r"data = \x30\x31")
        assert a.generate("data") == b.generate("data") == b"01"

    def test_bare_word_is_still_a_rule_reference(self):
        """The fix must not turn bare words into literals."""
        g = Grammar()
        g.parse('top = inner\ninner = "x"')
        assert g.generate("top") == b"x"

    def test_undefined_reference_warns(self, caplog):
        g = Grammar()
        g.parse("top = nonexistent_rule")
        with caplog.at_level(logging.WARNING, logger="fuzzer_tool.core.grammar"):
            out = g.generate("top")
        assert out == b"?"
        assert any("unknown rule" in r.message.lower() for r in caplog.records)


class TestShippedGrammars:
    @pytest.mark.parametrize(
        "name,magic",
        [
            ("png.gram", b"\x89PNG\r\n\x1a\n"),
            ("jpeg.gram", b"\xff\xd8"),
            ("rar.gram", b"Rar!\x1a\x07"),
        ],
    )
    def test_declared_magic_is_generated(self, name, magic):
        g = load_grammar(os.path.join(_DICT_DIR, name))
        for _ in range(20):
            assert magic in g.generate(max_len=4096)

    @pytest.mark.parametrize("name", ["png.gram", "jpeg.gram", "der.gram", "rar.gram"])
    def test_no_undefined_references(self, name):
        g = load_grammar(os.path.join(_DICT_DIR, name))
        undefined = {
            tok[1]
            for alts in g.rules.values()
            for alt in alts
            for tok in alt
            if tok[0] in ("ref", "repeat") and tok[1] not in g.rules
        }
        assert not undefined, f"{name} references undefined rules: {sorted(undefined)}"

    @pytest.mark.parametrize("name", ["png.gram", "jpeg.gram", "der.gram", "rar.gram"])
    def test_no_literal_backslash_x_leaks_into_output(self, name):
        r"""A generation containing the ASCII text \x means an escape was
        emitted as characters rather than decoded."""
        g = load_grammar(os.path.join(_DICT_DIR, name))
        for _ in range(20):
            assert rb"\x" not in g.generate(max_len=4096)

    def test_png_chunk_names_are_present(self):
        g = load_grammar(os.path.join(_DICT_DIR, "png.gram"))
        seen = b"".join(g.generate(max_len=4096) for _ in range(40))
        assert b"IHDR" in seen
        assert b"IEND" in seen
