"""Berlekamp-Massey algorithm for linear complexity analysis and LFSR recovery.

The BM algorithm finds the minimal linear feedback shift register (LFSR)
that generates a given binary sequence over GF(2).  The LFSR length *L* is
the *linear complexity* of the sequence — a measure of structure that
complements Shannon entropy and FFT periodicity: a sequence can look
uniform under both entropy and periodicity checks while still being
generated by a short linear recurrence, which only BM catches.

Two use cases are implemented:

1. **Checksum recovery** — from ``(data, checksum)`` pairs, recover the
   linear polynomial used to compute the checksum.  Independent pairs use
   a GCD-of-syndromes approach over GF(2); sequential outputs (e.g. a
   running CRC over message prefixes) use the classic BM algorithm.
2. **Structuredness metric** — ``linear_complexity()`` gives the BM LFSR
   length for an arbitrary byte sequence, usable as a third axis in
   structural analysis alongside ``shannon_entropy`` and
   ``detect_periodicity``.
"""

from __future__ import annotations

from collections.abc import Sequence

from fuzzer_tool.core.gf2_common import poly_gcd

# ---------------------------------------------------------------------------
# Bit-reversal helpers (shared by compute_checksum's reflect_out and by
# recover_polynomial_gcd's reflected-domain support, below).
# ---------------------------------------------------------------------------


def _reverse_bits(x: int, width: int) -> int:
    """Reverse the low *width* bits of *x*."""
    result = 0
    for _ in range(width):
        result = (result << 1) | (x & 1)
        x >>= 1
    return result


def _reverse_byte(b: int) -> int:
    """Reverse the bits of a single byte (0-255)."""
    return _reverse_bits(b, 8)


# ---------------------------------------------------------------------------
# Core BM algorithm over GF(2)
# ---------------------------------------------------------------------------


def berlekamp_massey(bits: Sequence[int]) -> tuple[int, list[int]]:
    """Berlekamp-Massey algorithm over GF(2).

    Finds the shortest LFSR that generates the given binary sequence.

    Args:
        bits: Binary sequence (0s and 1s).

    Returns:
        ``(L, C)`` where *L* is the minimal LFSR length and *C* is the
        connection-polynomial coefficients ``[c0, c1, ..., cL]`` with
        ``c0 = 1``.  The recurrence is::

            s_n = c1*s_{n-1} + c2*s_{n-2} + ... + cL*s_{n-L}
    """
    n = len(bits)
    C: list[int] = [1]  # current connection polynomial
    B: list[int] = [1]  # backup copy of C before last update
    L = 0  # current LFSR length
    m = 1  # distance since last update

    for n_idx in range(n):
        # Discrepancy: expected vs actual
        d = bits[n_idx]
        for i in range(1, L + 1):
            d ^= C[i] * bits[n_idx - i]

        if d == 1:
            T = C[:]  # save current C
            # C = C + x^m * B  (polynomial addition = XOR)
            len_b = len(B)
            extend = len_b + m - len(C)
            if extend > 0:
                C.extend([0] * extend)
            for i in range(len_b):
                C[i + m] ^= B[i]
            if n_idx // 2 >= L:
                L = n_idx + 1 - L
                B = T
                m = 1
            else:
                m += 1
        else:
            m += 1

    return L, C


# ---------------------------------------------------------------------------
# Structuredness metric
# ---------------------------------------------------------------------------


def linear_complexity(bits: Sequence[int]) -> int:
    """Linear complexity of a binary sequence.

    The length of the shortest LFSR that generates the sequence.  A
    sequence with linear complexity close to its length is *complex* in
    the linear-algebra sense; a short LFSR means the sequence is highly
    structured despite possibly looking random under Shannon entropy or
    FFT periodicity.
    """
    L, _ = berlekamp_massey(bits)
    return L


def sequence_linear_complexity(data: bytes) -> int:
    """Linear complexity of an arbitrary byte sequence.

    Convenience wrapper that converts bytes to bits and calls
    ``linear_complexity``.
    """
    return linear_complexity(_bytes_to_bits(data))


# ---------------------------------------------------------------------------
# Bit / integer conversion helpers
# ---------------------------------------------------------------------------


def _bytes_to_bits(data: bytes) -> list[int]:
    """Convert bytes to a list of bits (MSB-first per byte)."""
    bits: list[int] = []
    for byte in data:
        for i in range(7, -1, -1):
            bits.append((byte >> i) & 1)
    return bits


# ---------------------------------------------------------------------------
# LFSR helpers
# ---------------------------------------------------------------------------


def recover_lfsr(values: list[int], width: int = 32) -> int | None:
    """Recover an LFSR connection polynomial from sequential state *values*.

    *values* must be the raw register states of a reflected (LSB-first)
    LFSR taken one step apart — e.g. ``[state0, lfsr_step(state0, poly),
    ...]``.  Only the lane-0 bit stream (the bit shifted out at each step)
    is used: every other lane is a time-shift of it, so concatenating all
    lanes would multiply the linear complexity by *width* and hide the
    generator.

    Args:
        values: Observed sequential LFSR state values.
        width: Bit width of each value.

    Returns:
        Connection polynomial in the **reversed** form accepted by
        :func:`lfsr_step` and ``compute_checksum(..., reflect_in=True)``
        (e.g. ``0xEDB88320`` for standard CRC-32), or ``None`` if the
        recovered recurrence is degenerate or wider than *width*.
    """
    if len(values) < 2:
        return None
    # Lane 0 = the shifted-out bit — the LFSR output stream.
    bits = [v & 1 for v in values]
    L, C = berlekamp_massey(bits)
    if L == 0 or width < L:
        return None
    normal = 0
    for i in range(1, L + 1):
        if C[i]:
            normal |= 1 << (width - i)
    # Lane-0 BM recovers the normal-form generator; the LFSR's reflected
    # (reversed) form is its bit-reversal.
    return int(f"{normal:0{width}b}"[::-1], 2)


def lfsr_step(state: int, poly: int, width: int = 32) -> int:
    """Single LFSR step (LSB-first, right-shift, feedback when LSB=1).

    This matches the reflected CRC algorithm: the connection polynomial
    *poly* is the **reversed** form (bit 0 = ``x^width`` coefficient,
    bit width-1 = ``x^1`` coefficient).  When the LSB is 1, the
    reflected polynomial is XORed in before the shift.
    """
    mask = (1 << width) - 1
    feedback = (state & 1) * poly
    return ((state >> 1) ^ feedback) & mask


def lfsr_generate(seed: int, poly: int, n: int, width: int = 32) -> list[int]:
    """Generate *n* output bits from an LFSR.

    Each step shifts the register right; the bit shifted out (LSB before
    the shift) is the output.
    """
    mask = (1 << width) - 1
    state = seed & mask
    outputs: list[int] = []
    for _ in range(n):
        outputs.append(state & 1)
        state = lfsr_step(state, poly, width)
    return outputs


# ---------------------------------------------------------------------------
# Checksum computation from a recovered polynomial
# ---------------------------------------------------------------------------


def compute_checksum(
    data: bytes,
    poly: int,
    width: int = 32,
    init: int = 0,
    final_xor: int = 0,
    reflect_in: bool = False,
    reflect_out: bool = False,
) -> int:
    """Compute a CRC-like checksum over *data* using a recovered polynomial.

    Two shift conventions are supported:

    **Non-reflected (MSB-first)** — ``reflect_in=False``: each byte is
    XORed into the top ``width-8`` bits; the register shifts left 8 times
    with the polynomial XORed in when the MSB is 1.  *poly* is the normal
    form, e.g. ``0x04C11DB7``.

    **Reflected (LSB-first)** — ``reflect_in=True``: each byte is XORed
    into the bottom 8 bits; the register shifts right 8 times with the
    polynomial XORed in when the LSB is 1.  *poly* is the reversed form,
    e.g. ``0xEDB88320`` (the bit-reversal of the normal form).

    Args:
        data: Input bytes.
        poly: Connection polynomial.  Normal form for non-reflected,
            reversed form for reflected.
        width: Checksum width in bits (8, 16, 32).
        init: Initial register value.
        final_xor: Final XOR applied to the register before returning.
        reflect_in: Use the reflected (LSB-first) algorithm.
        reflect_out: Bit-reverse the final result before final_xor.

    Returns:
        Checksum as an unsigned integer.
    """
    mask = (1 << width) - 1
    reg = init & mask

    if reflect_in:
        for byte in data:
            reg ^= byte
            for _ in range(8):
                feedback = (reg & 1) * poly
                reg = ((reg >> 1) ^ feedback) & mask
        result = reg & mask
    else:
        for byte in data:
            reg ^= byte << (width - 8)
            for _ in range(8):
                msb = (reg >> (width - 1)) & 1
                reg = ((reg << 1) ^ (msb * poly)) & mask
        result = reg & mask

    if reflect_out:
        result = _reverse_bits(result, width)
    return (result ^ final_xor) & mask


# ---------------------------------------------------------------------------
# Polynomial GCD (for independent-pair recovery)
# ---------------------------------------------------------------------------


def recover_polynomial_gcd(
    pairs: list[tuple[bytes, int]],
    width: int = 32,
    init: int = 0,
    final_xor: int = 0,
    reflected: bool = False,
) -> int | None:
    """Recover a CRC polynomial from independent ``(data, checksum)`` pairs.

    For each pair ``(M, C)``, the syndrome is::

        D = M(x) * x^W + C  (mod 2)

    The generator polynomial *G(x)* divides every syndrome when the CRC
    uses ``init=0`` and ``final_xor=0``.  For other configurations, the
    caller should adjust the pairs so the syndrome formula holds, or
    iterate over common ``(init, final_xor)`` combinations.

    This handles the non-reflected (MSB-first) case directly. Virtually
    every real-world CRC-32 in the wild — zlib, gzip, PNG, ZIP, Ethernet —
    is *reflected* (LSB-first shifting, reversed-form polynomial like
    ``0xEDB88320``), which this syndrome formula does not directly apply
    to. Pass ``reflected=True`` for that case: reflected CRC computation
    is mathematically equivalent to the non-reflected algorithm run on
    each input byte with its own bits reversed (byte *order* unchanged),
    using the bit-reversed (normal-form) polynomial, with the checksum,
    init, and final_xor also bit-reversed — this transform is applied
    here, the non-reflected recovery runs on the transformed pairs, and
    the recovered polynomial is bit-reversed back to reflected form
    before returning. Verified against ``compute_checksum(reflect_in=True)``
    in ``tests/test_berlekamp_massey.py``.

    Args:
        pairs: ``(data, checksum)`` tuples.  *data* is the bytes that
            went into the checksum; *checksum* is the observed value.
        width: Checksum width in bits.
        init: CRC init value (assumed known; subtracted from the syndrome).
        final_xor: CRC final XOR (assumed known; subtracted).
        reflected: True if the checksum uses reflected (LSB-first) shifting
            — the overwhelmingly common case for real-world CRC-32s.

    Returns:
        Generator polynomial, masked to *width* bits (reflected form if
        ``reflected=True``, normal form otherwise), or ``None`` if fewer
        than 2 pairs are available.
    """
    if len(pairs) < 2:
        return None

    if reflected:
        transformed = [
            (bytes(_reverse_byte(b) for b in data), _reverse_bits(crc, width))
            for data, crc in pairs
        ]
        poly = recover_polynomial_gcd(
            transformed,
            width=width,
            init=_reverse_bits(init, width),
            final_xor=_reverse_bits(final_xor, width),
            reflected=False,
        )
        return _reverse_bits(poly, width) if poly is not None else None

    syndromes: list[int] = []
    for data, crc in pairs:
        M = int.from_bytes(data, "big")
        # D = M(x)*x^W + (crc XOR final_xor) XOR init
        D = (M << width) ^ (crc ^ final_xor) ^ init
        syndromes.append(D)

    result = syndromes[0]
    for s in syndromes[1:]:
        if result == 0:
            result = s
        elif s != 0:
            result = poly_gcd(result, s)
    if not result:
        return None
    # The generator has degree exactly `width`, so bit `width` is always
    # set in the raw GCD result. Mask it off to match the conventional
    # truncated representation (e.g. 0xEDB88320, not 0x1EDB88320) that
    # compute_checksum() and every CRC reference table use.
    return result & ((1 << width) - 1)
