"""Generic Floyd cycle detection (tortoise and hare) over any state sequence.

Floyd's algorithm finds the cycle in a sequence x0, f(x0), f(f(x0)), ...
in O(1) extra state and O(mu + lambda) calls to ``step``, where ``mu`` is
the tail length before the cycle starts and ``lambda`` is the cycle
length. The tradeoff against the obvious "keep a set/dict of every state
you've seen" approach is exactly that: O(1) memory instead of O(mu +
lambda) memory, paid for with roughly 3x the ``step`` calls (the hare
moves twice as fast, plus a second full pass to locate ``mu``). It is
only worth reaching for when either the state is expensive to hash/store
in bulk, or the sequence is long enough that the memory difference
actually matters — for short sequences a plain seen-set is simpler and
just as cheap.

Two call sites in this project have a real (not textbook-only) need for
it, because both feed a sequence generated by repeated application of a
fixed step function and both currently have no way to tell "still slowly
converging" apart from "will never converge, it's oscillating":

1. ``core/schedulers/monte_carlo.py`` power iteration for the operator
   transition chain's stationary distribution. A periodic chain (e.g. an
   exact period-2 alternation between two operators) never satisfies the
   L1-tolerance convergence check and silently burns the full iteration
   budget, returning whatever the iterate happens to be at cutoff instead
   of the actually-correct Cesaro (time) average over the limit cycle.
2. A bounded regression smoke-test for ``core/rand_pool.py`` (see
   ``tools/audit_randpool_cycle.py``): not a full-period audit (RandPool
   delegates to numpy's PCG64, whose period is 2**128 and is not
   something any algorithm can exhaustively verify), but a cheap guard
   against the actual bug class this project cares about — a stream that
   degenerates into a *short* repeat (e.g. a broken reseed, or two pool
   instances started from the same effective state after a fork).

State equality is caller-supplied (``is_close``) rather than assumed to
be ``==`` because the two use cases above compare floating-point vectors
and raw integers respectively, with different tolerance needs.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Generic, TypeVar

T = TypeVar("T")

IsClose = Callable[[T, T], bool]
Step = Callable[[T], T]

# Default cap on total `step` calls across all three passes. Chosen so a
# caller who forgets to bound `max_steps` on a genuinely non-cyclic (or
# very-long-tailed) sequence fails fast rather than looping effectively
# forever; callers with a legitimately larger state space should pass an
# explicit `max_steps`.
DEFAULT_MAX_STEPS = 100_000


@dataclass(frozen=True)
class CycleResult(Generic[T]):
    """A detected cycle in the sequence x0, step(x0), step(step(x0)), ...

    Attributes:
        mu: Length of the tail before the cycle starts (index of the
            first state that is part of the cycle).
        period: Length of the cycle itself (lambda in the usual
            tortoise/hare notation).
        state: The state at index `mu` — i.e. the representative state
            the cycle starts at. Feeding this back into `step` `period`
            times returns to `state` (up to `is_close`).
    """

    mu: int
    period: int
    state: T


def floyd_detect(
    x0: T,
    step: Step[T],
    is_close: IsClose[T],
    max_steps: int = DEFAULT_MAX_STEPS,
) -> CycleResult[T] | None:
    """Detect a cycle in the sequence generated by repeated `step` calls.

    Standard three-phase Floyd's algorithm:

    1. Advance tortoise by 1 and hare by 2 until they collide (`is_close`
       true) — proves a cycle exists and gives a meeting point somewhere
       inside it, but not `mu` or `period` directly.
    2. Reset tortoise to `x0`, keep hare at the meeting point, advance
       both by 1 in lockstep until they collide again — the collision
       index is exactly `mu` (a standard but non-obvious property of the
       algorithm: the distance from x0 to the cycle start equals the
       distance from the phase-1 meeting point to the cycle start,
       modulo the period).
    3. From the confirmed cycle-start state, advance a second pointer
       until it returns to that state — the step count is `period`.

    Args:
        x0: Starting state.
        step: Deterministic state transition function.
        is_close: Equality test tolerant of whatever noise the state
            representation has (exact `==` for hashable discrete state,
            a tolerance-based comparison for float vectors).
        max_steps: Upper bound on total `step` calls across all phases,
            per phase (i.e. each of the three phases gets its own budget)
            — a non-cyclic or long-tailed sequence returns None rather
            than looping unboundedly.

    Returns:
        A `CycleResult` if a cycle was found within budget, else None
        (no cycle detected — either the sequence is genuinely acyclic
        within the search horizon, or `max_steps` was too small).
    """
    # Phase 1: find a meeting point inside the cycle.
    tortoise = step(x0)
    hare = step(step(x0))
    calls = 0
    while not is_close(tortoise, hare):
        tortoise = step(tortoise)
        hare = step(step(hare))
        calls += 3
        if calls > max_steps:
            return None

    # Phase 2: locate the cycle start (mu).
    mu = 0
    tortoise = x0
    calls = 0
    while not is_close(tortoise, hare):
        tortoise = step(tortoise)
        hare = step(hare)
        mu += 1
        calls += 2
        if calls > max_steps:
            return None

    # Phase 3: measure the cycle length (period) from the confirmed start.
    period = 1
    hare = step(tortoise)
    calls = 0
    while not is_close(tortoise, hare):
        hare = step(hare)
        period += 1
        calls += 1
        if calls > max_steps:
            return None

    return CycleResult(mu=mu, period=period, state=tortoise)


def cesaro_average(
    state: T,
    step: Step[T],
    period: int,
    add: Callable[[T, T], T] | None = None,
    scale: Callable[[T, float], T] | None = None,
) -> T:
    """Average `state` and its next `period - 1` iterates under `step`.

    For a state stuck in an exact limit cycle (the correct outcome of
    periodic power iteration — see module docstring, use case 1), no
    single iterate is "the" stationary point; their time-average over one
    full period is. This is the discrete analogue of the Cesaro mean used
    to assign a limit to a non-convergent-but-bounded sequence.

    Args:
        state: A state that is part of the cycle (e.g. `CycleResult.state`).
        step: Same step function used to detect the cycle.
        period: Cycle length (e.g. `CycleResult.period`).
        add: Binary addition for the state type. Defaults to `+`.
        scale: `(state, factor) -> state` scalar scaling. Defaults to `*`.

    Returns:
        The averaged state. For numpy arrays or plain floats/lists that
        support `+` and `*` directly, the defaults work unmodified.
    """
    add_fn: Callable[[T, T], T] = add or (lambda a, b: a + b)  # type: ignore[operator]
    scale_fn: Callable[[T, float], T] = scale or (lambda a, k: a * k)  # type: ignore[operator,assignment,return-value]

    total = state
    current = state
    for _ in range(period - 1):
        current = step(current)
        total = add_fn(total, current)
    return scale_fn(total, 1.0 / period)
