"""Structure-aware / grammar mutations for structured inputs.

Provides a simple grammar specification format and mutation operators
that generate structurally valid inputs for protocols, file formats, etc.

Grammar format (S-expression style):
    <rule_name> = <alt1> | <alt2> | ...
    <rule_name> = <literal>          # fixed bytes
    <rule_name> = <rule_ref>{N}      # repeat N times
    <rule_name> = <rule_ref>+        # repeat 1-8 times
    <rule_name> = <rule_ref>*        # repeat 0-8 times
    <rule_name> = <rule_ref>{N,M}    # repeat N to M times

Example (HTTP request):
    request = method SP uri SP version CRLF headers CRLF body
    method  = GET | POST | PUT | DELETE | HEAD
    uri     = / | /api/v1 | /index.html
    version = HTTP/1.0 | HTTP/1.1 | HTTP/2
    CRLF    = \r\n
    SP      = \x20
    headers = header*
    header  = name ": " value CRLF
    name    = Host | Content-Type | Accept | Authorization
    value   = localhost | application/json | text/html | Bearer
    body    = {} | {"key":"value"} | <html></html>
"""

import logging
import random
import re
from pathlib import Path

log = logging.getLogger(__name__)


class Grammar:
    """Simple grammar-based generator and mutator.

    Rules are stored as a dict of rule_name -> list of alternatives.
    Each alternative is a list of tokens (literals, refs, or quantifiers).
    """

    def __init__(self):
        self.rules: dict[str, list[list]] = {}
        self.max_depth = 10

    def parse(self, spec: str):
        """Parse a grammar specification string.

        Args:
            spec: Grammar specification in the S-expression format.
        """
        for line in spec.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            name, body = line.split("=", 1)
            name = name.strip()
            body = body.strip()

            alternatives = []
            for alt in body.split("|"):
                alt = alt.strip()
                if not alt:
                    continue
                alternatives.append(self._parse_alternative(alt))

            if alternatives:
                self.rules[name] = alternatives

    def parse_file(self, path: str):
        """Parse a grammar file.

        Args:
            path: Path to grammar specification file.
        """
        text = Path(path).read_text(errors="replace")
        self.parse(text)

    def _parse_alternative(self, alt: str) -> list:
        """Parse a single alternative into a list of tokens."""
        tokens = []
        # Match: "literal", rule_ref, rule_ref{N}, rule_ref{N,M}, rule_ref+, rule_ref*
        pattern = re.compile(
            r'"([^"]*)"'  # quoted literal
            r"|'([^']*)'"  # single-quoted literal
            r"|(\w+)\{(\d+),(\d+)\}"  # {N,M}
            r"|(\w+)\{(\d+)\}"  # {N}
            r"|(\w+)\+"  # +
            r"|(\w+)\*"  # *
            r"|(\w+)"  # bare rule_ref
        )
        _MAX_REPEAT = 32
        for m in pattern.finditer(alt):
            if m.group(1) is not None:
                tokens.append(("lit", bytes(m.group(1), "utf-8")))
            elif m.group(2) is not None:
                tokens.append(("lit", bytes(m.group(2), "utf-8")))
            elif m.group(3) is not None:
                lo, hi = int(m.group(4)), int(m.group(5))
                tokens.append(("repeat", m.group(3), min(lo, _MAX_REPEAT), min(hi, _MAX_REPEAT)))
            elif m.group(6) is not None:
                n = min(int(m.group(7)), _MAX_REPEAT)
                tokens.append(("repeat", m.group(6), n, n))
            elif m.group(8) is not None:
                tokens.append(("repeat", m.group(8), 1, 8))
            elif m.group(9) is not None:
                tokens.append(("repeat", m.group(9), 0, 8))
            elif m.group(10) is not None:
                tokens.append(("ref", m.group(10)))
        return tokens

    def generate(self, rule: str = None, max_depth: int = None, max_len: int = 0) -> bytes:
        """Generate a random input from the grammar.

        Args:
            rule: Starting rule name. If None, uses the first rule.
            max_depth: Maximum recursion depth.
            max_len: If > 0, truncate output to this length.

        Returns:
            Generated bytes.
        """
        if not self.rules:
            return b""

        if rule is None:
            rule = next(iter(self.rules))

        if max_depth is None:
            max_depth = self.max_depth

        result = self._expand_rule(rule, max_depth)
        if max_len > 0:
            result = result[:max_len]
        return result

    def _expand_rule(self, name: str, depth: int) -> bytes:
        """Expand a rule into bytes."""
        if depth <= 0 or name not in self.rules:
            if depth <= 0:
                log.warning("Grammar recursion depth exhausted at rule '%s' — possible cyclic grammar", name)
            else:
                log.debug("Grammar unknown rule: %s (depth=%d)", name, depth)
            return b"?"

        alts = self.rules[name]
        alt = random.choice(alts)
        return self._expand_tokens(alt, depth)

    def _expand_tokens(self, tokens: list, depth: int) -> bytes:
        """Expand a list of tokens into bytes."""
        result = b""
        for token in tokens:
            kind = token[0]
            if kind == "lit":
                result += token[1]
            elif kind == "ref":
                result += self._expand_rule(token[1], depth - 1)
            elif kind == "repeat":
                _, name, lo, hi = token
                count = random.randint(lo, hi)
                for _ in range(count):
                    result += self._expand_rule(name, depth - 1)
        return result

    def mutate(self, data: bytes, max_len: int = 4096) -> bytes:
        """Mutate an input using grammar-aware operations.

        Applies grammar-specific mutations that respect structure:
        1. Subtree replacement: regenerate a random subexpression
        2. Literal perturbation: flip/corrupt bytes in literals
        3. Repetition count change: add/remove repeated elements
        4. Field truncation: shorten a field
        5. Field extension: lengthen a field

        Args:
            data: Input bytes to mutate.
            max_len: Maximum output length.

        Returns:
            Mutated bytes.
        """
        if not self.rules or not data:
            return data

        op = random.randint(0, 4)
        if op == 0:
            return self._mutate_literal(data, max_len)
        elif op == 1:
            return self._mutate_truncate(data)
        elif op == 2:
            return self._mutate_extend(data, max_len)
        elif op == 3:
            return self._mutate_insert(data, max_len)
        else:
            return self._mutate_replace_section(data, max_len)

    def _mutate_literal(self, data: bytes, max_len: int) -> bytes:
        """Flip or replace bytes in the input."""
        if not data:
            return self.generate(max_len=max_len)

        buf = bytearray(data)
        idx = random.randint(0, len(buf) - 1)
        op = random.randint(0, 3)
        if op == 0:
            buf[idx] ^= 1 << random.randint(0, 7)
        elif op == 1:
            buf[idx] = random.randint(0, 255)
        elif op == 2:
            buf[idx] = random.choice([0, 1, 0x7F, 0x80, 0xFF])
        else:
            # Replace with a printable ASCII character
            buf[idx] = random.randint(0x20, 0x7E)
        return bytes(buf[:max_len])

    def _mutate_truncate(self, data: bytes) -> bytes:
        """Truncate the input at a random point."""
        if len(data) <= 1:
            return data
        cut = random.randint(1, len(data) - 1)
        return data[:cut]

    def _mutate_extend(self, data: bytes, max_len: int) -> bytes:
        """Extend the input with generated bytes."""
        extra = self.generate()[:64]
        if len(data) + len(extra) > max_len:
            extra = extra[: max_len - len(data)]
        pos = random.randint(0, len(data))
        return data[:pos] + extra + data[pos:]

    def _mutate_insert(self, data: bytes, max_len: int) -> bytes:
        """Insert a generated fragment at a random position."""
        fragment = self.generate()[:32]
        if len(data) + len(fragment) > max_len:
            fragment = fragment[: max_len - len(data)]
        pos = random.randint(0, len(data))
        return data[:pos] + fragment + data[pos:]

    def _mutate_replace_section(self, data: bytes, max_len: int) -> bytes:
        """Replace a random section with generated bytes."""
        if len(data) <= 1:
            return self.generate(max_len=max_len)
        start = random.randint(0, len(data) - 1)
        end = random.randint(start + 1, min(start + 32, len(data)))
        replacement = self.generate()[: end - start]
        return data[:start] + replacement + data[end:]


# Built-in grammar specs for common formats
GRAMMARS = {
    "json": """
# Simple JSON grammar
json    = value
value   = object | array | string | number | "true" | "false" | "null"
object  = "{" "}"
array   = "[" "]"
string  = "\\"" text "\\""
text    = word* | ""
word    = letter | digit | space
letter  = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
digit   = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
space   = \\x20 | \\t
""",
    "http_request": """
# HTTP request grammar
request = method SP uri SP version CRLF headers CRLF body
method  = GET | POST | PUT | DELETE | HEAD | PATCH
uri     = / | /api | /api/v1 | /index.html | /health | /debug
version = HTTP/1.0 | HTTP/1.1
CRLF    = \\r\\n
SP      = \\x20
headers = header*
header  = name ":" SP value CRLF
name    = Host | Content-Type | Accept | Authorization | X-Request-ID | User-Agent
value   = localhost | application/json | text/html | application/octet-stream | Bearer | close
body    = {} | {"key":"value"} | data=12345
""",
    "elf": """
# Minimal ELF header
magic   = \\x7f ELF
class   = \\x01 | \\x02
data    = \\x01
version = \\x01
osabi   = \\x00 | \\x03 | \\x06 | \\x09
padding = \\x00{8}
""",
}


def load_grammar(spec: str | Path) -> Grammar:
    """Load a grammar from a spec string or file path.

    If the spec is a known name (e.g., 'json', 'http_request', 'elf'),
    loads the built-in grammar. If it's a file path, reads the file.

    Args:
        spec: Grammar name or file path.

    Returns:
        Parsed Grammar object.
    """
    g = Grammar()
    if isinstance(spec, str) and spec in GRAMMARS:
        g.parse(GRAMMARS[spec])
    elif isinstance(spec, Path) or (isinstance(spec, str) and Path(spec).is_file()):
        g.parse_file(str(spec))
    else:
        # Try as inline spec
        g.parse(str(spec))
    return g
