"""Structure-aware / grammar mutations for structured inputs.

Provides a simple grammar specification format and mutation operators
that generate structurally valid inputs for protocols, file formats, etc.

Grammar format (S-expression style):
    <rule_name> = <alt1> | <alt2> | ...
    <rule_name> = <literal>          # fixed bytes
    <rule_name> = <rule_ref>{N}      # repeat N times
    <rule_name> = <rule_ref>+        # repeat 1-8 times
    <rule_name> = <rule_ref>*        # repeat 0-8 times
    <rule_name> = <rule_ref>{N,M}    # repeat N to M times

Example (HTTP request):
    request = method SP uri SP version CRLF headers CRLF body
    method  = GET | POST | PUT | DELETE | HEAD
    uri     = / | /api/v1 | /index.html
    version = HTTP/1.0 | HTTP/1.1 | HTTP/2
    CRLF    = \r\n
    SP      = \x20
    headers = header*
    header  = name ": " value CRLF
    name    = Host | Content-Type | Accept | Authorization
    value   = localhost | application/json | text/html | Bearer
    body    = {} | {"key":"value"} | <html></html>
"""

import logging
import random
import re
import struct
from pathlib import Path

log = logging.getLogger(__name__)


class Grammar:
    """Simple grammar-based generator and mutator.

    Rules are stored as a dict of rule_name -> list of alternatives.
    Each alternative is a list of tokens (literals, refs, or quantifiers).
    """

    def __init__(self):
        self.rules: dict[str, list[list]] = {}
        self.max_depth = 10

    def parse(self, spec: str):
        """Parse a grammar specification string.

        Args:
            spec: Grammar specification in the S-expression format.
        """
        for line in spec.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            name, body = line.split("=", 1)
            name = name.strip()
            body = body.strip()

            alternatives = []
            for alt in body.split("|"):
                alt = alt.strip()
                if not alt:
                    continue
                alternatives.append(self._parse_alternative(alt))

            if alternatives:
                self.rules[name] = alternatives

    def parse_file(self, path: str):
        """Parse a grammar file.

        Args:
            path: Path to grammar specification file.
        """
        text = Path(path).read_text(errors="replace")
        self.parse(text)

    def _parse_alternative(self, alt: str) -> list:
        """Parse a single alternative into a list of tokens."""
        tokens = []
        # Match: "literal", rule_ref, rule_ref{N}, rule_ref{N,M}, rule_ref+, rule_ref*
        pattern = re.compile(
            r'"([^"]*)"'  # quoted literal
            r"|'([^']*)'"  # single-quoted literal
            r"|(\w+)\{(\d+),(\d+)\}"  # {N,M}
            r"|(\w+)\{(\d+)\}"  # {N}
            r"|(\w+)\+"  # +
            r"|(\w+)\*"  # *
            r"|(\w+)"  # bare rule_ref
        )
        _MAX_REPEAT = 32
        for m in pattern.finditer(alt):
            if m.group(1) is not None:
                tokens.append(("lit", bytes(m.group(1), "utf-8")))
            elif m.group(2) is not None:
                tokens.append(("lit", bytes(m.group(2), "utf-8")))
            elif m.group(3) is not None:
                lo, hi = int(m.group(4)), int(m.group(5))
                tokens.append(("repeat", m.group(3), min(lo, _MAX_REPEAT), min(hi, _MAX_REPEAT)))
            elif m.group(6) is not None:
                n = min(int(m.group(7)), _MAX_REPEAT)
                tokens.append(("repeat", m.group(6), n, n))
            elif m.group(8) is not None:
                tokens.append(("repeat", m.group(8), 1, 8))
            elif m.group(9) is not None:
                tokens.append(("repeat", m.group(9), 0, 8))
            elif m.group(10) is not None:
                tokens.append(("ref", m.group(10)))
        return tokens

    def generate(self, rule: str = None, max_depth: int = None, max_len: int = 0) -> bytes:
        """Generate a random input from the grammar.

        Args:
            rule: Starting rule name. If None, uses the first rule.
            max_depth: Maximum recursion depth.
            max_len: If > 0, truncate output to this length.

        Returns:
            Generated bytes.
        """
        if not self.rules:
            return b""

        if rule is None:
            rule = next(iter(self.rules))

        if max_depth is None:
            max_depth = self.max_depth

        result = self._expand_rule(rule, max_depth)
        if max_len > 0:
            result = result[:max_len]
        return result

    def _expand_rule(self, name: str, depth: int) -> bytes:
        """Expand a rule into bytes."""
        if depth <= 0 or name not in self.rules:
            if depth <= 0:
                log.warning("Grammar recursion depth exhausted at rule '%s' — possible cyclic grammar", name)
            else:
                log.debug("Grammar unknown rule: %s (depth=%d)", name, depth)
            return b"?"

        alts = self.rules[name]
        alt = random.choice(alts)
        return self._expand_tokens(alt, depth)

    def _expand_tokens(self, tokens: list, depth: int) -> bytes:
        """Expand a list of tokens into bytes."""
        result = b""
        for token in tokens:
            kind = token[0]
            if kind == "lit":
                result += token[1]
            elif kind == "ref":
                result += self._expand_rule(token[1], depth - 1)
            elif kind == "repeat":
                _, name, lo, hi = token
                count = random.randint(lo, hi)
                for _ in range(count):
                    result += self._expand_rule(name, depth - 1)
        return result

    def mutate(self, data: bytes, max_len: int = 4096) -> bytes:
        """Mutate an input using grammar-aware operations.

        Applies grammar-specific mutations that respect structure:
        1. Subtree replacement: regenerate a random subexpression
        2. Literal perturbation: flip/corrupt bytes in literals
        3. Repetition count change: add/remove repeated elements
        4. Field truncation: shorten a field
        5. Field extension: lengthen a field

        Args:
            data: Input bytes to mutate.
            max_len: Maximum output length.

        Returns:
            Mutated bytes.
        """
        if not self.rules or not data:
            return data

        op = random.randint(0, 4)
        if op == 0:
            return self._mutate_literal(data, max_len)
        elif op == 1:
            return self._mutate_truncate(data)
        elif op == 2:
            return self._mutate_extend(data, max_len)
        elif op == 3:
            return self._mutate_insert(data, max_len)
        else:
            return self._mutate_replace_section(data, max_len)

    def _mutate_literal(self, data: bytes, max_len: int) -> bytes:
        """Flip or replace bytes in the input."""
        if not data:
            return self.generate(max_len=max_len)

        buf = bytearray(data)
        idx = random.randint(0, len(buf) - 1)
        op = random.randint(0, 3)
        if op == 0:
            buf[idx] ^= 1 << random.randint(0, 7)
        elif op == 1:
            buf[idx] = random.randint(0, 255)
        elif op == 2:
            buf[idx] = random.choice([0, 1, 0x7F, 0x80, 0xFF])
        else:
            # Replace with a printable ASCII character
            buf[idx] = random.randint(0x20, 0x7E)
        return bytes(buf[:max_len])

    def _mutate_truncate(self, data: bytes) -> bytes:
        """Truncate the input at a random point."""
        if len(data) <= 1:
            return data
        cut = random.randint(1, len(data) - 1)
        return data[:cut]

    def _mutate_extend(self, data: bytes, max_len: int) -> bytes:
        """Extend the input with generated bytes."""
        extra = self.generate()[:64]
        if len(data) + len(extra) > max_len:
            extra = extra[: max_len - len(data)]
        pos = random.randint(0, len(data))
        return data[:pos] + extra + data[pos:]

    def _mutate_insert(self, data: bytes, max_len: int) -> bytes:
        """Insert a generated fragment at a random position."""
        fragment = self.generate()[:32]
        if len(data) + len(fragment) > max_len:
            fragment = fragment[: max_len - len(data)]
        pos = random.randint(0, len(data))
        return data[:pos] + fragment + data[pos:]

    def _mutate_replace_section(self, data: bytes, max_len: int) -> bytes:
        """Replace a random section with generated bytes."""
        if len(data) <= 1:
            return self.generate(max_len=max_len)
        start = random.randint(0, len(data) - 1)
        end = random.randint(start + 1, min(start + 32, len(data)))
        replacement = self.generate()[: end - start]
        return data[:start] + replacement + data[end:]


# Built-in grammar specs for common formats
GRAMMARS = {
    "json": """
# Simple JSON grammar
json    = value
value   = object | array | string | number | "true" | "false" | "null"
object  = "{" "}"
array   = "[" "]"
string  = "\\"" text "\\""
text    = word* | ""
word    = letter | digit | space
letter  = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
digit   = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
space   = \\x20 | \\t
""",
    "http_request": """
# HTTP request grammar
request = method SP uri SP version CRLF headers CRLF body
method  = GET | POST | PUT | DELETE | HEAD | PATCH
uri     = / | /api | /api/v1 | /index.html | /health | /debug
version = HTTP/1.0 | HTTP/1.1
CRLF    = \\r\\n
SP      = \\x20
headers = header*
header  = name ":" SP value CRLF
name    = Host | Content-Type | Accept | Authorization | X-Request-ID | User-Agent
value   = localhost | application/json | text/html | application/octet-stream | Bearer | close
body    = {} | {"key":"value"} | data=12345
""",
    "elf": """
# Minimal ELF header
magic   = \\x7f ELF
class   = \\x01 | \\x02
data    = \\x01
version = \\x01
osabi   = \\x00 | \\x03 | \\x06 | \\x09
padding = \\x00{8}
""",
}


def load_grammar(spec: str | Path) -> Grammar:
    """Load a grammar from a spec string or file path.

    If the spec is a known name (e.g., 'json', 'http_request', 'elf'),
    loads the built-in grammar. If it's a file path, reads the file.

    Args:
        spec: Grammar name or file path.

    Returns:
        Parsed Grammar object.
    """
    g = Grammar()
    if isinstance(spec, str) and spec in GRAMMARS:
        g.parse(GRAMMARS[spec])
    elif isinstance(spec, Path) or (isinstance(spec, str) and Path(spec).is_file()):
        g.parse_file(str(spec))
    else:
        # Try as inline spec
        g.parse(str(spec))
    return g


# ---------------------------------------------------------------------------
# Tree-level AST and mutations (Superion/Nautilus-style)
# ---------------------------------------------------------------------------

class TreeNode:
    """Node in a parse tree for grammar-aware mutation.

    A leaf node holds raw bytes. An interior node holds a rule name and
    a list of child TreeNodes. The tree mirrors the grammar's structure:
    each interior node corresponds to a nonterminal expansion.
    """

    __slots__ = ("rule", "children", "data")

    def __init__(self, rule: str = "", children: list | None = None, data: bytes = b""):
        self.rule = rule
        self.children = children or []
        self.data = data  # only for leaf nodes

    @property
    def is_leaf(self) -> bool:
        return not self.children and bool(self.data)

    def serialize(self) -> bytes:
        """Serialize the tree back to bytes."""
        if self.is_leaf:
            return self.data
        parts = []
        for child in self.children:
            parts.append(child.serialize())
        return b"".join(parts)

    def size(self) -> int:
        """Number of nodes in this subtree."""
        if self.is_leaf:
            return 1
        return 1 + sum(c.size() for c in self.children)

    def depth(self) -> int:
        if self.is_leaf:
            return 0
        return 1 + max(c.depth() for c in self.children) if self.children else 0

    def collect_interior(self, rule: str | None = None) -> list["TreeNode"]:
        """Collect all interior nodes (optionally filtered by rule name)."""
        result = []
        if not self.is_leaf:
            if rule is None or self.rule == rule:
                result.append(self)
            for child in self.children:
                result.extend(child.collect_interior(rule))
        return result

    def collect_leaves(self) -> list["TreeNode"]:
        if self.is_leaf:
            return [self]
        result = []
        for child in self.children:
            result.extend(child.collect_leaves())
        return result

    def all_nodes(self) -> list["TreeNode"]:
        result = [self]
        for child in self.children:
            result.extend(child.all_nodes())
        return result

    def _find_path(self, target: "TreeNode", path: list | None = None) -> list | None:
        """Find the path from root to target node."""
        if path is None:
            path = []
        if self is target:
            return path
        for i, child in enumerate(self.children):
            found = child._find_path(target, path + [i])
            if found is not None:
                return found
        return None

    def __repr__(self):
        if self.is_leaf:
            preview = self.data[:20]
            return f"Leaf({self.rule!r}, {preview!r}...)"
        return f"Node({self.rule!r}, children={len(self.children)})"


class TreeMutator:
    """Parse inputs against a grammar into trees and mutate at the tree level.

    Produces mutations that respect the grammar's structure — swapping two
    subtrees of the same nonterminal type, duplicating a node, deleting a
    subtree, or splicing in a subtree from a different corpus entry.
    """

    def __init__(self, grammar: Grammar):
        self.grammar = grammar
        # Known structural delimiters for heuristic parsing
        self._delimiters: dict[str, tuple[bytes, bytes]] = {
            "json": (b"{", b"}"),
            "array": (b"[", b"]"),
        }

    def parse(self, data: bytes, rule: str | None = None) -> TreeNode:
        """Heuristic parse of input bytes into a tree structure.

        Uses grammar rule knowledge to identify structural boundaries.
        For well-known formats (JSON, XML), uses delimiter matching.
        For unknown formats, segments by fixed-size chunks from grammar
        quantifiers.
        """
        if rule is None:
            rule = next(iter(self.grammar.rules)) if self.grammar.rules else "root"

        if not data:
            return TreeNode(rule=rule, data=b"")

        # Try structured parsing for known formats
        tree = self._parse_structured(data, rule)
        if tree is not None:
            return tree

        # Fallback: segment by grammar-inferred chunk sizes
        return self._parse_chunked(data, rule)

    def _parse_structured(self, data: bytes, rule: str) -> TreeNode | None:
        """Parse structured formats using delimiter matching."""
        # JSON-like: { ... } or [ ... ]
        if data.startswith(b"{") and data.endswith(b"}"):
            return self._parse_braced(data, rule, b"{", b"}")
        if data.startswith(b"[") and data.endswith(b"]"):
            return self._parse_braced(data, rule, b"[", b"]")
        return None

    def _parse_braced(self, data: bytes, rule: str, open_b: bytes, close_b: bytes) -> TreeNode:
        """Parse braced content into a tree with children for each element."""
        children = []
        # Opening delimiter
        children.append(TreeNode(rule="delim", data=open_b))

        # Parse contents: split by top-level commas (for JSON objects/arrays)
        inner = data[len(open_b):-len(close_b)] if len(data) > len(open_b) + len(close_b) else b""
        if inner:
            elements = self._split_top_level(inner)
            for elem in elements:
                elem = elem.strip()
                if not elem:
                    continue
                child_rule = self._infer_rule(elem)
                children.append(self.parse(elem, child_rule))

        # Closing delimiter
        children.append(TreeNode(rule="delim", data=close_b))
        return TreeNode(rule=rule, children=children)

    def _split_top_level(self, data: bytes) -> list[bytes]:
        """Split by comma at the top nesting level only."""
        result = []
        depth = 0
        current = bytearray()
        in_string = False
        escape_next = False
        for b in data:
            if escape_next:
                current.append(b)
                escape_next = False
                continue
            if b == ord("\\") and in_string:
                current.append(b)
                escape_next = True
                continue
            if b == ord('"'):
                in_string = not in_string
            if not in_string:
                if b in (ord("{"), ord("[")):
                    depth += 1
                elif b in (ord("}"), ord("]")):
                    depth -= 1
                elif b == ord(",") and depth == 0:
                    result.append(bytes(current))
                    current = bytearray()
                    continue
            current.append(b)
        if current:
            result.append(bytes(current))
        return result

    def _infer_rule(self, data: bytes) -> str:
        """Infer which grammar rule a byte fragment likely matches."""
        data = data.strip()
        if data.startswith(b'"') and data.endswith(b'"'):
            return "string"
        if data.startswith(b"{"):
            return "object"
        if data.startswith(b"["):
            return "array"
        if data in (b"true", b"false", b"null"):
            return "value"
        try:
            float(data)
            return "number"
        except (ValueError, UnicodeDecodeError):
            pass
        return "value"

    def _parse_chunked(self, data: bytes, rule: str) -> TreeNode:
        """Fallback: segment input into fixed-size chunks based on grammar."""
        # Infer chunk size from grammar quantifiers
        chunk_size = self._infer_chunk_size()
        if chunk_size <= 0 or len(data) <= chunk_size:
            return TreeNode(rule=rule, data=data)

        children = []
        for i in range(0, len(data), chunk_size):
            chunk = data[i : i + chunk_size]
            child_rule = self._infer_rule(chunk)
            children.append(TreeNode(rule=child_rule, data=chunk))
        return TreeNode(rule=rule, children=children)

    def _infer_chunk_size(self) -> int:
        """Infer a reasonable chunk size from grammar quantifiers."""
        for alts in self.grammar.rules.values():
            for alt in alts:
                for token in alt:
                    if token[0] == "repeat":
                        # Use the repeat body's typical expansion as chunk size
                        return 16  # reasonable default for structured fields
        return 16

    # ------------------------------------------------------------------
    # Tree-level mutations
    # ------------------------------------------------------------------

    def mutate_tree(self, tree: TreeNode, max_len: int = 4096) -> bytes:
        """Apply a random tree-level mutation and serialize back to bytes.

        Operations:
        1. Subtree swap: replace a node with a freshly generated subtree
           of the same rule type
        2. Subtree delete: remove a node (replace with empty)
        3. Subtree duplicate: clone a node and insert the copy nearby
        4. Subtree splice: replace a node with a subtree from another
           corpus entry's tree
        5. Rule substitution: replace a node with a different alternative
           from the same grammar rule
        """
        if tree.is_leaf:
            return self._mutate_leaf(tree, max_len)

        op = random.randint(0, 4)
        if op == 0:
            return self._tree_swap(tree, max_len)
        elif op == 1:
            return self._tree_delete(tree, max_len)
        elif op == 2:
            return self._tree_duplicate(tree, max_len)
        elif op == 3:
            return self._tree_rule_sub(tree, max_len)
        else:
            return self._mutate_leaf(tree, max_len)

    def _tree_swap(self, tree: TreeNode, max_len: int) -> bytes:
        """Replace a random interior node with a freshly generated subtree."""
        targets = tree.collect_interior()
        if not targets:
            return tree.serialize()[:max_len]
        target = random.choice(targets)
        # Generate a replacement of the same rule type
        replacement_bytes = self.grammar.generate(target.rule, max_len=max_len)
        replacement = TreeNode(rule=target.rule, data=replacement_bytes)
        # Replace in parent
        self._replace_in_tree(tree, target, replacement)
        return tree.serialize()[:max_len]

    def _tree_delete(self, tree: TreeNode, max_len: int) -> bytes:
        """Remove a random non-root interior node."""
        # Collect interior nodes that aren't the root
        all_interior = tree.collect_interior()
        candidates = [n for n in all_interior if n is not tree and n.children]
        if not candidates:
            return tree.serialize()[:max_len]
        target = random.choice(candidates)
        # Replace with empty leaf
        self._replace_in_tree(tree, target, TreeNode(rule=target.rule, data=b""))
        return tree.serialize()[:max_len]

    def _tree_duplicate(self, tree: TreeNode, max_len: int) -> bytes:
        """Clone a random node and insert the copy as a sibling."""
        # Find a parent with multiple children
        all_interior = tree.collect_interior()
        parents_with_children = [n for n in all_interior if len(n.children) >= 2]
        if not parents_with_children:
            return tree.serialize()[:max_len]
        parent = random.choice(parents_with_children)
        idx = random.randint(0, len(parent.children) - 1)
        clone = self._clone_tree(parent.children[idx])
        # Insert after the original
        parent.children.insert(idx + 1, clone)
        return tree.serialize()[:max_len]

    def _tree_rule_sub(self, tree: TreeNode, max_len: int) -> bytes:
        """Replace a node with a different alternative from the same rule."""
        targets = tree.collect_interior()
        # Filter to rules with multiple alternatives
        multi_targets = [
            n for n in targets
            if n.rule in self.grammar.rules and len(self.grammar.rules[n.rule]) > 1
        ]
        if not multi_targets:
            return tree.serialize()[:max_len]
        target = random.choice(multi_targets)
        replacement_bytes = self.grammar.generate(target.rule, max_len=max_len)
        self._replace_in_tree(tree, target, TreeNode(rule=target.rule, data=replacement_bytes))
        return tree.serialize()[:max_len]

    def _mutate_leaf(self, tree: TreeNode, max_len: int) -> bytes:
        """Byte-level mutation on a leaf node."""
        data = tree.serialize()
        if not data:
            return self.grammar.generate(max_len=max_len)
        buf = bytearray(data)
        idx = random.randint(0, len(buf) - 1)
        buf[idx] ^= 1 << random.randint(0, 7)
        return bytes(buf[:max_len])

    def _replace_in_tree(self, root: TreeNode, old: TreeNode, new: TreeNode):
        """Replace old node with new in root's tree."""
        for i, child in enumerate(root.children):
            if child is old:
                root.children[i] = new
                return True
            if self._replace_in_tree(child, old, new):
                return True
        return False

    def _clone_tree(self, node: TreeNode) -> TreeNode:
        """Deep-clone a tree node."""
        if node.is_leaf:
            return TreeNode(rule=node.rule, data=node.data)
        return TreeNode(
            rule=node.rule,
            children=[self._clone_tree(c) for c in node.children],
        )

    # ------------------------------------------------------------------
    # Hierarchical delta debugging for tmin
    # ------------------------------------------------------------------

    def hierarchical_shrink(self, data: bytes, still_crashes, max_rounds: int = 64) -> bytes:
        """Shrink a crashing input by removing whole tree-level chunks first.

        Tries removing each nonterminal subtree before falling back to
        byte-level reduction. Converges to a minimal reproducer that's
        structurally meaningful.

        Args:
            data: The crashing input.
            still_crashes: Callable(bytes) -> bool — returns True if input still crashes.
            max_rounds: Maximum reduction rounds.

        Returns:
            Minimized bytes.
        """
        best = data
        for _ in range(max_rounds):
            tree = self.parse(best)
            # Collect all non-root interior nodes with children
            candidates = [
                n for n in tree.collect_interior()
                if n is not tree and n.children
            ]
            if not candidates:
                break

            improved = False
            for node in candidates:
                # Try removing this subtree
                clone = self._clone_tree(tree)
                # Find the same node in the clone
                path = tree._find_path(node)
                if path is None:
                    continue
                clone_node = clone
                for idx in path[:-1]:
                    clone_node = clone_node.children[idx]
                target_idx = path[-1]
                # Replace with empty
                clone_node.children[target_idx] = TreeNode(
                    rule=node.rule, data=b""
                )
                candidate = clone.serialize()
                if candidate and candidate != best and still_crashes(candidate):
                    best = candidate
                    improved = True
                    break  # restart with smaller tree

            if not improved:
                break


# ---------------------------------------------------------------------------
# PNG format-aware mutations
# ---------------------------------------------------------------------------

# PNG chunk types that control code paths in libpng
_IHDR_TYPES = {b"IHDR", b"PLTE", b"tRNS", b"IDAT", b"IEND",
               b"bKGD", b"cHRM", b"gAMA", b"hIST", b"iCCP",
               b"sBIT", b"sCAL", b"pHYs", b"sPLT", b"tEXt",
               b"iTXt", b"zTXt", b"fdAT", b"fcTL"}

# Valid IHDR bit depths per color type
_IHDR_BIT_DEPTHS = {
    0: [1, 2, 4, 8, 16],       # grayscale
    2: [8, 16],                  # RGB
    3: [1, 2, 4, 8],             # indexed
    4: [8, 16],                  # grayscale+alpha
    6: [8, 16],                  # RGBA
}

# Valid color types
_IHDR_COLOR_TYPES = [0, 2, 3, 4, 6]


class PngChunk:
    """A single PNG chunk: type(4) + data(length) + crc(4)."""
    __slots__ = ("chunk_type", "data")

    def __init__(self, chunk_type: bytes, data: bytes):
        self.chunk_type = chunk_type
        self.data = data

    def serialize(self) -> bytes:
        length = struct.pack(">I", len(self.data))
        crc = struct.pack(">I", self._compute_crc())
        return length + self.chunk_type + self.data + crc

    def _compute_crc(self) -> int:
        import zlib
        return zlib.crc32(self.chunk_type + self.data) & 0xFFFFFFFF


def parse_png_chunks(data: bytes) -> list[PngChunk] | None:
    """Parse PNG data into a list of chunks. Returns None if invalid."""
    if len(data) < 8 or data[:8] != b"\x89PNG\r\n\x1a\n":
        return None

    chunks = []
    pos = 8
    while pos + 8 <= len(data):
        if pos + 8 > len(data):
            break
        length = struct.unpack_from(">I", data, pos)[0]
        chunk_type = data[pos + 4 : pos + 8]

        if pos + 12 + length > len(data):
            break  # truncated

        chunk_data = data[pos + 8 : pos + 8 + length]
        chunks.append(PngChunk(chunk_type, chunk_data))
        pos += 12 + length  # 4(len) + 4(type) + data + 4(crc)

        if chunk_type == b"IEND":
            break

    return chunks if chunks else None


def serialize_png_chunks(chunks: list[PngChunk]) -> bytes:
    """Serialize chunks back to PNG bytes."""
    result = b"\x89PNG\r\n\x1a\n"
    for chunk in chunks:
        result += chunk.serialize()
    return result


class PngChunkMutator:
    """Format-aware mutations for PNG files.

    Operates on parsed PNG chunks to produce mutations that respect
    the PNG structure while exercising different code paths in libpng:

    1. IHDR field mutations — change width/height/bit_depth/color_type
       to trigger different decompression paths
    2. PLTE mutations — corrupt palette entries for indexed-color PNGs
    3. IDAT mutations — corrupt compressed data to trigger inflate errors
    4. Chunk duplication — duplicate IDAT/PLTE to test chunk counting
    5. Chunk deletion — remove required chunks to test error handling
    6. Chunk reordering — swap chunk order to test parser robustness
    7. CRC corruption — break CRC validation paths
    8. Length manipulation — lie about chunk data length
    """

    def mutate(self, data: bytes, max_len: int = 4096) -> bytes:
        """Apply a random format-aware PNG mutation."""
        chunks = parse_png_chunks(data)
        if not chunks:
            return self._generate_random_png(max_len)

        op = random.randint(0, 27)
        if op == 0:
            return self._mutate_ihdr(chunks, max_len)
        elif op == 1:
            return self._mutate_plte(chunks, max_len)
        elif op == 2:
            return self._mutate_idat(chunks, max_len)
        elif op == 3:
            return self._duplicate_chunk(chunks, max_len)
        elif op == 4:
            return self._delete_chunk(chunks, max_len)
        elif op == 5:
            return self._reorder_chunks(chunks, max_len)
        elif op == 6:
            return self._corrupt_crc(chunks, max_len)
        elif op == 7:
            return self._mutate_length(chunks, max_len)
        elif op == 8:
            return self._split_idat(chunks, max_len)
        elif op == 9:
            return self._mutate_filter(chunks, max_len)
        elif op == 10:
            return self._mutate_interlace(chunks, max_len)
        elif op == 11:
            return self._add_empty_chunks(chunks, max_len)
        elif op == 12:
            return self._corrupt_signature(data, max_len)
        elif op == 13:
            return self._mutate_idat_multi(chunks, max_len)
        elif op == 14:
            return self._mutate_color_depth(chunks, max_len)
        elif op == 15:
            return self._large_input(chunks, max_len)
        elif op == 16:
            return self._add_trns(chunks, max_len)
        elif op == 17:
            return self._mutate_ancillary(chunks, max_len)
        elif op == 18:
            return self._micro_idat(chunks, max_len)
        elif op == 19:
            return self._duplicate_ihdr(chunks, max_len)
        elif op == 20:
            return self._move_after_iend(chunks, max_len)
        elif op == 21:
            return self._mutate_chrm(chunks, max_len)
        elif op == 22:
            return self._mutate_sbit(chunks, max_len)
        elif op == 23:
            return self._mutate_iccp(chunks, max_len)
        elif op == 24:
            return self._duplicate_plte(chunks, max_len)
        elif op == 25:
            return self._corrupt_idat_data(chunks, max_len)
        elif op == 26:
            return self._extreme_dimensions(chunks, max_len)
        else:
            return self._generate_random_png(max_len)

        op = random.randint(0, 21)
        if op == 0:
            return self._mutate_ihdr(chunks, max_len)
        elif op == 1:
            return self._mutate_plte(chunks, max_len)
        elif op == 2:
            return self._mutate_idat(chunks, max_len)
        elif op == 3:
            return self._duplicate_chunk(chunks, max_len)
        elif op == 4:
            return self._delete_chunk(chunks, max_len)
        elif op == 5:
            return self._reorder_chunks(chunks, max_len)
        elif op == 6:
            return self._corrupt_crc(chunks, max_len)
        elif op == 7:
            return self._mutate_length(chunks, max_len)
        elif op == 8:
            return self._split_idat(chunks, max_len)
        elif op == 9:
            return self._mutate_filter(chunks, max_len)
        elif op == 10:
            return self._mutate_interlace(chunks, max_len)
        elif op == 11:
            return self._add_empty_chunks(chunks, max_len)
        elif op == 12:
            return self._corrupt_signature(data, max_len)
        elif op == 13:
            return self._mutate_idat_multi(chunks, max_len)
        elif op == 14:
            return self._mutate_color_depth(chunks, max_len)
        elif op == 15:
            return self._large_input(chunks, max_len)
        elif op == 16:
            return self._add_trns(chunks, max_len)
        elif op == 17:
            return self._mutate_ancillary(chunks, max_len)
        elif op == 18:
            return self._micro_idat(chunks, max_len)
        elif op == 19:
            return self._duplicate_ihdr(chunks, max_len)
        elif op == 20:
            return self._move_after_iend(chunks, max_len)
        else:
            return self._generate_random_png(max_len)

    def _mutate_ihdr(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Mutate IHDR fields: width, height, bit_depth, color_type."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        if not ihdr or len(ihdr.data) < 13:
            return serialize_png_chunks(chunks)[:max_len]

        d = bytearray(ihdr.data)
        field = random.randint(0, 4)
        if field == 0:  # width
            w = struct.unpack_from(">I", d, 0)[0]
            w = self._mutate_int(w, 0, 65535)
            struct.pack_into(">I", d, 0, w)
        elif field == 1:  # height
            h = struct.unpack_from(">I", d, 4)[0]
            h = self._mutate_int(h, 0, 65535)
            struct.pack_into(">I", d, 4, h)
        elif field == 2:  # bit_depth
            ct = d[6]
            valid = _IHDR_BIT_DEPTHS.get(ct, [8])
            d[7] = random.choice(valid + [0, 32, 128, 255])  # include invalid
        elif field == 3:  # color_type
            d[6] = random.choice(_IHDR_COLOR_TYPES + [1, 5, 7, 128, 255])
        else:  # compression, filter, interlace
            d[8 + field - 4] = random.randint(0, 255)

        ihdr.data = bytes(d)
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_plte(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Mutate PLTE palette entries or create a PLTE chunk."""
        plte = self._find_chunk(chunks, b"PLTE")
        if plte and len(plte.data) >= 3:
            # Mutate random palette entry
            d = bytearray(plte.data)
            idx = random.randint(0, len(d) // 3 - 1) * 3
            for i in range(3):
                d[idx + i] = random.randint(0, 255)
            plte.data = bytes(d)
        else:
            # Insert a PLTE chunk before first IDAT
            idat_idx = self._find_chunk_index(chunks, b"IDAT")
            if idat_idx >= 0:
                plte_data = bytes(random.randint(0, 255) for _ in range(768))
                chunks.insert(idat_idx, PngChunk(b"PLTE", plte_data))

        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_idat(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Mutate IDAT compressed data to trigger inflate errors."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat or len(idat.data) < 2:
            return serialize_png_chunks(chunks)[:max_len]

        d = bytearray(idat.data)
        if random.random() < 0.3:
            # Corrupt zlib header (first 2 bytes)
            d[0] = random.randint(0, 255)
            d[1] = random.randint(0, 255)
        else:
            # Flip random byte in compressed data
            idx = random.randint(0, len(d) - 1)
            d[idx] ^= random.randint(1, 255)

        idat.data = bytes(d)
        return serialize_png_chunks(chunks)[:max_len]

    def _duplicate_chunk(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Duplicate a random chunk (tests chunk counting)."""
        if len(chunks) < 2:
            return serialize_png_chunks(chunks)[:max_len]

        idx = random.randint(1, len(chunks) - 1)  # skip IHDR
        clone = PngChunk(chunks[idx].chunk_type, chunks[idx].data)
        insert_at = random.randint(idx, len(chunks))
        chunks.insert(insert_at, clone)
        return serialize_png_chunks(chunks)[:max_len]

    def _delete_chunk(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Delete a random non-IHDR chunk."""
        if len(chunks) < 3:
            return serialize_png_chunks(chunks)[:max_len]

        candidates = [(i, c) for i, c in enumerate(chunks) if c.chunk_type != b"IHDR"]
        if candidates:
            idx, _ = random.choice(candidates)
            del chunks[idx]
        return serialize_png_chunks(chunks)[:max_len]

    def _reorder_chunks(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Swap two random chunks (tests parser order-sensitivity)."""
        if len(chunks) < 3:
            return serialize_png_chunks(chunks)[:max_len]

        i = random.randint(1, len(chunks) - 2)
        j = random.randint(i + 1, len(chunks) - 1)
        chunks[i], chunks[j] = chunks[j], chunks[i]
        return serialize_png_chunks(chunks)[:max_len]

    def _corrupt_crc(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Corrupt a chunk's CRC (tests CRC validation paths)."""
        if not chunks:
            return serialize_png_chunks(chunks)[:max_len]

        idx = random.randint(0, len(chunks) - 1)
        # Serialize with corrupted CRC by manipulating the raw bytes
        result = b"\x89PNG\r\n\x1a\n"
        for i, chunk in enumerate(chunks):
            length = struct.pack(">I", len(chunk.data))
            if i == idx:
                # Write wrong CRC
                crc = struct.pack(">I", random.randint(0, 0xFFFFFFFF))
            else:
                crc = struct.pack(">I", chunk._compute_crc())
            result += length + chunk.chunk_type + chunk.data + crc
            if chunk.chunk_type == b"IEND":
                break
        return result[:max_len]

    def _mutate_length(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Lie about a chunk's data length."""
        if not chunks:
            return serialize_png_chunks(chunks)[:max_len]

        idx = random.randint(0, len(chunks) - 1)
        result = b"\x89PNG\r\n\x1a\n"
        for i, chunk in enumerate(chunks):
            if i == idx:
                # Write wrong length (too long or too short)
                fake_len = random.choice([
                    len(chunk.data) + random.randint(1, 100),
                    max(0, len(chunk.data) - random.randint(0, min(10, len(chunk.data)))),
                ])
                length = struct.pack(">I", fake_len)
            else:
                length = struct.pack(">I", len(chunk.data))
            crc = struct.pack(">I", chunk._compute_crc())
            result += length + chunk.chunk_type + chunk.data + crc
            if chunk.chunk_type == b"IEND":
                break
        return result[:max_len]

    def _split_idat(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Split one IDAT into multiple chunks (tests chunk assembly)."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat or len(idat.data) < 4:
            return serialize_png_chunks(chunks)[:max_len]

        d = idat.data
        n_chunks = random.randint(2, min(4, len(d)))
        chunk_size = len(d) // n_chunks
        pieces = []
        for i in range(n_chunks):
            start = i * chunk_size
            end = start + chunk_size if i < n_chunks - 1 else len(d)
            pieces.append(PngChunk(b"IDAT", d[start:end]))

        idx = chunks.index(idat)
        chunks[idx:idx + 1] = pieces
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_filter(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Mutate PNG row filter type (first byte of each scanline)."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat or len(idat.data) < 2:
            return serialize_png_chunks(chunks)[:max_len]

        import zlib
        try:
            raw = zlib.decompress(idat.data)
        except zlib.error:
            return serialize_png_chunks(chunks)[:max_len]

        if len(raw) < 2:
            return serialize_png_chunks(chunks)[:max_len]

        ihdr = self._find_chunk(chunks, b"IHDR")
        if ihdr and len(ihdr.data) >= 9:
            width = struct.unpack_from(">I", ihdr.data, 0)[0]
            ct = ihdr.data[6]
            bd = ihdr.data[7]
            bpp = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}.get(ct, 4) * (bd // 8)
            stride = 1 + width * bpp
        else:
            stride = 4

        row_idx = random.randint(0, max(0, (len(raw) // stride) - 1)) if stride > 0 and len(raw) >= stride else 0
        filter_pos = row_idx * stride
        if filter_pos < len(raw):
            raw_list = bytearray(raw)
            raw_list[filter_pos] = random.randint(0, 8)
            raw = bytes(raw_list)

        try:
            idat.data = zlib.compress(raw)
        except zlib.error:
            pass
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_interlace(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Toggle Adam7 interlacing in IHDR."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        if not ihdr or len(ihdr.data) < 13:
            return serialize_png_chunks(chunks)[:max_len]

        d = bytearray(ihdr.data)
        d[12] = random.choice([0, 1])
        ihdr.data = bytes(d)
        return serialize_png_chunks(chunks)[:max_len]

    def _add_empty_chunks(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Add empty or truncated chunks to test error handling."""
        n = random.randint(1, 3)
        for _ in range(n):
            chunk_type = bytes([random.randint(0x41, 0x5A)] * 4)
            chunks.insert(random.randint(1, len(chunks)), PngChunk(chunk_type, b""))
        return serialize_png_chunks(chunks)[:max_len]

    def _corrupt_signature(self, data: bytes, max_len: int) -> bytes:
        """Corrupt PNG signature bytes."""
        if len(data) < 8:
            return self._generate_random_png(max_len)
        result = bytearray(data)
        n_corrupt = random.randint(1, 3)
        for _ in range(n_corrupt):
            result[random.randint(4, 7)] = random.randint(0, 255)
        return bytes(result)[:max_len]

    def _mutate_idat_multi(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Multiple IDAT mutations in one pass (complex combinations)."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat or len(idat.data) < 4:
            return serialize_png_chunks(chunks)[:max_len]

        d = bytearray(idat.data)
        for _ in range(random.randint(2, 4)):
            mut_type = random.randint(0, 2)
            if mut_type == 0:
                d[random.randint(0, len(d) - 1)] ^= random.randint(1, 255)
            elif mut_type == 1:
                d.insert(random.randint(0, len(d)), random.randint(0, 255))
            elif len(d) > 1:
                del d[random.randint(0, len(d) - 1)]

        idat.data = bytes(d)
        return serialize_png_chunks(chunks)[:max_len]

    def _generate_random_png(self, max_len: int) -> bytes:
        """Generate a minimal valid PNG for mutation seeding."""
        # Minimal IHDR: 1x1, 8-bit RGBA
        ihdr_data = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
        ihdr = PngChunk(b"IHDR", ihdr_data)
        # Minimal IDAT: single filter byte (none) + 4 bytes (RGBA pixel)
        import zlib
        raw = b"\x00\x80\x00\x00\x80"  # filter=none + RGBA pixel
        idat_data = zlib.compress(raw)
        idat = PngChunk(b"IDAT", idat_data)
        iend = PngChunk(b"IEND", b"")
        return serialize_png_chunks([ihdr, idat, iend])[:max_len]

    @staticmethod
    def _find_chunk(chunks: list[PngChunk], chunk_type: bytes) -> PngChunk | None:
        for c in chunks:
            if c.chunk_type == chunk_type:
                return c
        return None

    @staticmethod
    def _find_chunk_index(chunks: list[PngChunk], chunk_type: bytes) -> int:
        for i, c in enumerate(chunks):
            if c.chunk_type == chunk_type:
                return i
        return -1

    @staticmethod
    def _mutate_int(val: int, lo: int, hi: int) -> int:
        """Mutate an integer with various strategies."""
        op = random.randint(0, 4)
        if op == 0:
            return random.randint(lo, hi)
        elif op == 1:
            return 0
        elif op == 2:
            return max(lo, min(hi, val + random.randint(-10, 10)))
        elif op == 3:
            return max(lo, min(hi, val ^ (1 << random.randint(0, 31))))
        else:
            return max(lo, min(hi, val * 2))

    def _add_trns(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Add tRNS (transparency) chunk — triggers alpha/transparency code paths."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        ct = ihdr.data[6] if ihdr and len(ihdr.data) >= 7 else 2

        # tRNS format depends on color type
        if ct == 0:  # grayscale: 2-byte value
            trns_data = struct.pack(">H", random.randint(0, 65535))
        elif ct == 2:  # RGB: 6-byte value
            trns_data = struct.pack(">HHH",
                random.randint(0, 65535),
                random.randint(0, 65535),
                random.randint(0, 65535))
        elif ct == 3:  # palette: up to 256 alpha values
            n = random.randint(1, 8)
            trns_data = bytes(random.randint(0, 255) for _ in range(n))
        else:
            trns_data = b"\x00" * 2

        chunks.insert(random.randint(1, len(chunks)), PngChunk(b"tRNS", trns_data))
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_ancillary(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Mutate ancillary chunk values (gAMA, cHRM, pHYs, sRGB)."""
        # Add or mutate gAMA (gamma value, 4 bytes)
        if random.random() < 0.5:
            gama_value = random.choice([
                0x0000B18F,  # 1.0 gamma
                0x00002303,  # 0.4545 gamma
                0x00000000,  # zero gamma (invalid)
                0xFFFFFFFF,  # max gamma
                random.randint(0, 0xFFFFFFFF),
            ])
            gama_data = struct.pack(">I", gama_value)
            # Remove existing gAMA if present
            chunks = [c for c in chunks if c.chunk_type != b"gAMA"]
            chunks.insert(random.randint(1, len(chunks)), PngChunk(b"gAMA", gama_data))
        else:
            # Mutate pHYs (pixels per unit)
            phys_data = struct.pack(">IIB",
                random.randint(0, 10000),  # x
                random.randint(0, 10000),  # y
                random.choice([0, 1]))     # unit: 0=unknown, 1=meter
            chunks = [c for c in chunks if c.chunk_type != b"pHYs"]
            chunks.insert(random.randint(1, len(chunks)), PngChunk(b"pHYs", phys_data))

        return serialize_png_chunks(chunks)[:max_len]

    def _micro_idat(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Replace IDAT with minimal 1-byte compressed data (edge case in inflate)."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat:
            return serialize_png_chunks(chunks)[:max_len]

        # 1-byte zlib stream: just the header + empty block
        idat.data = b"\x78\x01\x03\x00\x00\x00\x00\x01"
        return serialize_png_chunks(chunks)[:max_len]

    def _duplicate_ihdr(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Duplicate the IHDR chunk (tests critical chunk duplication handling)."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        if not ihdr:
            return serialize_png_chunks(chunks)[:max_len]

        clone = PngChunk(b"IHDR", ihdr.data)
        chunks.insert(random.randint(0, len(chunks)), clone)
        return serialize_png_chunks(chunks)[:max_len]

    def _move_after_iend(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Move a chunk after IEND (tests IEND-not-last handling)."""
        if len(chunks) < 3:
            return serialize_png_chunks(chunks)[:max_len]

        # Find IEND
        iend_idx = -1
        for i, c in enumerate(chunks):
            if c.chunk_type == b"IEND":
                iend_idx = i
                break
        if iend_idx < 0:
            return serialize_png_chunks(chunks)[:max_len]

        # Pick a non-IEND, non-IHDR chunk to move
        candidates = [(i, c) for i, c in enumerate(chunks)
                      if c.chunk_type not in (b"IHDR", b"IEND")]
        if not candidates:
            return serialize_png_chunks(chunks)[:max_len]

        idx, chunk = random.choice(candidates)
        del chunks[idx]
        chunks.insert(iend_idx + 1, chunk)
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_chrm(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Add or mutate cHRM (chromaticity) chunk — tests color space handling."""
        chrm_data = struct.pack(">8I",
            random.randint(0, 100000),  # white point x
            random.randint(0, 100000),  # white point y
            random.randint(0, 100000),  # red x
            random.randint(0, 100000),  # red y
            random.randint(0, 100000),  # green x
            random.randint(0, 100000),  # green y
            random.randint(0, 100000),  # blue x
            random.randint(0, 100000),  # blue y
        )
        chunks = [c for c in chunks if c.chunk_type != b"cHRM"]
        chunks.insert(random.randint(1, len(chunks)), PngChunk(b"cHRM", chrm_data))
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_sbit(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Add or mutate sBIT (significant bits) chunk — tests precision handling."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        ct = ihdr.data[6] if ihdr and len(ihdr.data) >= 7 else 2

        if ct in (0, 4):  # grayscale or gray+alpha: 2 values
            sbit_data = bytes([random.randint(1, 16), random.randint(1, 16)])
        elif ct in (2, 6):  # RGB or RGBA: 4-6 values
            n = 4 if ct == 2 else 6
            sbit_data = bytes(random.randint(1, 16) for _ in range(n))
        elif ct == 3:  # palette: 3 values
            sbit_data = bytes(random.randint(1, 8) for _ in range(3))
        else:
            sbit_data = b"\x08" * 3

        chunks = [c for c in chunks if c.chunk_type != b"sBIT"]
        chunks.insert(random.randint(1, len(chunks)), PngChunk(b"sBIT", sbit_data))
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_iccp(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Add iCCP (ICC profile) chunk — tests color management paths."""
        # Minimal ICC profile: just a valid header
        iccp_name = b"icc"
        compression = 0  # zlib
        profile_data = zlib.compress(b"\x00" * 64) if 'zlib' in dir() else b"\x00" * 64
        iccp_data = iccp_name + bytes([compression]) + profile_data

        chunks = [c for c in chunks if c.chunk_type != b"iCCP"]
        chunks.insert(random.randint(1, len(chunks)), PngChunk(b"iCCP", iccp_data))
        return serialize_png_chunks(chunks)[:max_len]

    def _duplicate_plte(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Duplicate PLTE chunk — tests duplicate palette handling."""
        plte = self._find_chunk(chunks, b"PLTE")
        if not plte:
            return serialize_png_chunks(chunks)[:max_len]

        clone = PngChunk(b"PLTE", plte.data)
        idx = chunks.index(plte)
        chunks.insert(idx + 1, clone)
        return serialize_png_chunks(chunks)[:max_len]

    def _corrupt_idat_data(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Replace IDAT data with random bytes (tests inflate error handling)."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat:
            return serialize_png_chunks(chunks)[:max_len]

        # Replace with random bytes that look like zlib but aren't
        idat.data = bytes(random.randint(0, 255) for _ in range(random.randint(4, 32)))
        return serialize_png_chunks(chunks)[:max_len]

    def _extreme_dimensions(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Set extreme width/height values to test dimension handling."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        if not ihdr or len(ihdr.data) < 13:
            return serialize_png_chunks(chunks)[:max_len]

        d = bytearray(ihdr.data)
        # Set very large or very small dimensions
        dim = random.choice([
            (1, 1),      # minimal
            (1, 65535),  # max height
            (65535, 1),  # max width
            (10000, 10000),  # large square
        ])
        struct.pack_into(">I", d, 0, dim[0])
        struct.pack_into(">I", d, 4, dim[1])
        ihdr.data = bytes(d)
        return serialize_png_chunks(chunks)[:max_len]

    def _mutate_color_depth(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Force specific color_type + bit_depth combinations to test transform paths."""
        ihdr = self._find_chunk(chunks, b"IHDR")
        if not ihdr or len(ihdr.data) < 13:
            return serialize_png_chunks(chunks)[:max_len]

        # Valid combinations that exercise different transform paths
        combos = [
            (0, 1),   # grayscale 1-bit
            (0, 2),   # grayscale 2-bit
            (0, 4),   # grayscale 4-bit
            (0, 8),   # grayscale 8-bit
            (0, 16),  # grayscale 16-bit
            (2, 8),   # RGB 8-bit
            (2, 16),  # RGB 16-bit
            (3, 1),   # palette 1-bit
            (3, 2),   # palette 2-bit
            (3, 4),   # palette 4-bit
            (3, 8),   # palette 8-bit
            (4, 8),   # gray+alpha 8-bit
            (4, 16),  # gray+alpha 16-bit
            (6, 8),   # RGBA 8-bit
            (6, 16),  # RGBA 16-bit
            # Invalid combinations
            (0, 128), (2, 255), (6, 0), (3, 16),
        ]
        ct, bd = random.choice(combos)
        d = bytearray(ihdr.data)
        d[6] = ct
        d[7] = bd
        ihdr.data = bytes(d)
        return serialize_png_chunks(chunks)[:max_len]

    def _large_input(self, chunks: list[PngChunk], max_len: int) -> bytes:
        """Generate large IDAT data to trigger memory allocation paths."""
        idat = self._find_chunk(chunks, b"IDAT")
        if not idat:
            return serialize_png_chunks(chunks)[:max_len]

        import zlib
        # Create large raw data: fill with repeating pattern
        pattern = random.choice([
            b"\x00" * 64,      # zeros (compresses well)
            b"\xff" * 64,      # ones
            bytes(range(64)),   # sequential
            b"\x80" * 64,      # mid values
        ])
        # Scale to use most of max_len
        raw_size = max(1024, max_len // 4)
        raw = pattern * (raw_size // len(pattern) + 1)
        raw = raw[:raw_size]

        try:
            idat.data = zlib.compress(raw, 1)  # fast compression
        except zlib.error:
            pass
        return serialize_png_chunks(chunks)[:max_len]
