"""Byte-level Markov chain for fuzz input generation.

Tracks JS divergence between periodic transition snapshots to detect
plateaus — a flattening JS curve signals the mutation model has stopped
learning from new corpus entries.
"""

import collections
import json
import logging
import math
import random

from fuzzer_tool.core.edge_tracker import ks_significance_threshold

log = logging.getLogger(__name__)


class MarkovChain:
    """Byte-level Markov chain for fuzz input generation.

    Learns byte-level transition probabilities from training data and
    generates new inputs that follow the learned statistical patterns.

    Args:
        order: Number of previous bytes to use as context (n-gram order).
        smoothing: Laplace smoothing factor to avoid zero probabilities.

    Examples:
        >>> mc = MarkovChain(order=1)
        >>> mc.train(b"HTTP")
        >>> mc.is_trained()
        True
        >>> sample = mc.generate(4)
        >>> len(sample)
        4
    """

    def __init__(self, order: int = 1, smoothing: float = 1e-6):
        self.order = order
        self.smoothing = smoothing
        self.transitions: dict[bytes, collections.Counter] = collections.defaultdict(
            collections.Counter
        )
        self._contexts_seen = 0
        self._prev_snapshot: dict[bytes, dict[int, float]] | None = None
        self.last_js_divergence: float = 0.0
        self._snapshot_interval: int = 50  # snapshot every N train_corpus calls
        self._trains_since_snapshot: int = 0

    def train(self, data: bytes) -> None:
        """Learn byte transitions from a single input.

        Args:
            data: Raw bytes to train on.
        """
        for i in range(len(data)):
            ctx = bytes(data[max(0, i - self.order) : i]) if self.order else b""
            self.transitions[ctx][data[i]] += 1
            self._contexts_seen += 1

    def train_corpus(self, corpus: list[bytes]) -> None:
        """Train on multiple inputs.

        Args:
            corpus: List of byte sequences to train on.
        """
        for data in corpus:
            self.train(data)

    def generate(self, length: int) -> bytes:
        """Generate a new input of specified length from learned distribution.

        Args:
            length: Number of bytes to generate.

        Returns:
            Generated byte sequence.
        """
        result = bytearray()
        ctx = b"\x00" * self.order
        for _ in range(length):
            counts = self.transitions.get(ctx)
            if counts is None or not counts:
                result.append(random.randint(0, 255))
                ctx = bytes(result[max(0, len(result) - self.order) :])
                continue
            total = sum(counts.values()) + self.smoothing * 256
            r = random.random() * total
            cumulative = 0.0
            for byte_val, count in counts.items():
                cumulative += count + self.smoothing
                if r <= cumulative:
                    result.append(byte_val)
                    break
            else:
                result.append(random.randint(0, 255))
            ctx = bytes(result[max(0, len(result) - self.order) :])
        return bytes(result)

    def sample_byte(self, ctx: bytes) -> int:
        """Sample a single byte given a context window.

        Args:
            ctx: Context bytes (length should match order).

        Returns:
            Sampled byte value (0-255).
        """
        counts = self.transitions.get(ctx)
        if counts is None or not counts:
            return random.randint(0, 255)
        total = sum(counts.values()) + self.smoothing * 256
        r = random.random() * total
        cumulative = 0.0
        for byte_val, count in counts.items():
            cumulative += count + self.smoothing
            if r <= cumulative:
                return byte_val
        return random.randint(0, 255)

    def codelength(self, data: bytes) -> float:
        """Compute cross-entropy of input under the trained model (in bits).

        This is the MDL codelength: sum(-log2(P(byte|context))) for each byte.
        An input that the model considers "surprising" has high codelength —
        it's structurally novel relative to what the corpus has taught the model.
        An input the model can explain well has low codelength.

        Returns:
            Total codelength in bits. Higher = more surprising to the model.
        """
        if not self.transitions or not data:
            return len(data) * 8.0  # fall back to raw bit count

        total_bits = 0.0
        ctx = b"\x00" * self.order
        for i, byte_val in enumerate(data):
            counts = self.transitions.get(ctx)
            if counts is None or not counts:
                total_bits += 8.0  # uniform: log2(256) = 8 bits
            else:
                total = sum(counts.values()) + self.smoothing * 256
                p = (counts.get(byte_val, 0) + self.smoothing) / total
                total_bits += -math.log2(p)
            # Slide context window
            ctx = data[max(0, i + 1 - self.order) : i + 1]
        return total_bits

    def codelength_ratio(self, data: bytes) -> float:
        """Codelength per byte, normalized to [0, 8].

        0 = model predicts every byte perfectly (zero surprise).
        8 = model has no information (uniform random).
        > 8 = model is actively surprised (assigns low probability).
        """
        if not data:
            return 0.0
        return self.codelength(data) / len(data)

    def perplexity(self, data: bytes) -> float:
        """Perplexity of input under the trained model.

        PP = 2^(codelength_per_byte). Equivalent to: the model is as
        confused as if choosing uniformly from PP distinct outcomes.

        Returns:
            Perplexity in [1, 256+] range.
            1 = perfect prediction, 256 = uniform random byte,
            >256 = model is actively surprised.
        """
        if not data:
            return 1.0
        return 2.0 ** self.codelength_ratio(data)

    def corpus_perplexity(self, corpus: list[bytes]) -> dict:
        """Compute perplexity statistics across a corpus.

        Returns dict with:
          - mean: average perplexity
          - median: median perplexity
          - p10/p90: percentile values
          - low_surprise_count: seeds with PP < 10 (well-predicted)
          - high_surprise_count: seeds with PP > 200 (model is lost)
        """
        if not corpus:
            return {"mean": 0, "median": 0, "p10": 0, "p90": 0,
                    "low_surprise_count": 0, "high_surprise_count": 0}

        pps = [self.perplexity(seed) for seed in corpus[:200]]
        pps_sorted = sorted(pps)
        n = len(pps_sorted)

        return {
            "mean": sum(pps) / n,
            "median": pps_sorted[n // 2],
            "p10": pps_sorted[n // 10],
            "p90": pps_sorted[-n // 10],
            "low_surprise_count": sum(1 for p in pps if p < 10),
            "high_surprise_count": sum(1 for p in pps if p > 200),
        }

    def is_trained(self) -> bool:
        """Check if the chain has learned any transitions.

        Returns:
            True if any training data has been observed.
        """
        return self._contexts_seen > 0

    def snapshot_and_check_plateau(self) -> bool:
        """Snapshot current transitions and check if learning has plateaued.

        Computes JS divergence between the current transition distribution
        and the previous snapshot. A flattening JS curve (divergence → 0
        after initial high values) signals the model has stopped learning.

        Returns:
            True if plateau detected (JS divergence < 0.01 after at least
            2 snapshots), False otherwise.
        """
        self._trains_since_snapshot += 1
        if self._trains_since_snapshot < self._snapshot_interval:
            return False
        self._trains_since_snapshot = 0

        snapshot = self._build_snapshot()
        if self._prev_snapshot is not None:
            self.last_js_divergence = self._js_between_snapshots(
                self._prev_snapshot, snapshot
            )
        self._prev_snapshot = snapshot

        # Plateau: JS divergence is below what noise alone would produce
        # at this sample size — the distribution isn't meaningfully changing.
        # This replaces the fixed JS < 0.01 with a sample-size-aware threshold.
        threshold = ks_significance_threshold(
            self._contexts_seen, alpha=0.05
        )
        return (
            self._prev_snapshot is not None
            and self.last_js_divergence < threshold
            and self._contexts_seen > self._snapshot_interval * 2
        )

    def _build_snapshot(self) -> dict[bytes, dict[int, float]]:
        """Build a normalized snapshot of current transition distributions."""
        snapshot: dict[bytes, dict[int, float]] = {}
        for ctx, counts in self.transitions.items():
            total = sum(counts.values())
            if total > 0:
                snapshot[ctx] = {b: c / total for b, c in counts.items()}
        return snapshot

    @staticmethod
    def _js_between_snapshots(
        p: dict[bytes, dict[int, float]], q: dict[bytes, dict[int, float]]
    ) -> float:
        """JS divergence between two transition snapshots.

        Averages per-context JS across all contexts in either snapshot.
        """
        all_ctx = set(p) | set(q)
        js_values = []
        for ctx in all_ctx:
            p_dist = p.get(ctx, {})
            q_dist = q.get(ctx, {})
            if not p_dist and not q_dist:
                continue
            m: dict[int, float] = {}
            for b in set(p_dist) | set(q_dist):
                m[b] = 0.5 * (p_dist.get(b, 0.0) + q_dist.get(b, 0.0))

            def kl(a: dict[int, float], b: dict[int, float]) -> float:
                return sum(
                    pa * math.log(pa / b[k])
                    for k, pa in a.items()
                    if pa > 0.0 and b.get(k, 0.0) > 0.0
                )

            js_values.append(0.5 * kl(p_dist, m) + 0.5 * kl(q_dist, m))
        return sum(js_values) / len(js_values) if js_values else 0.0

    def save(self, path: str) -> bool:
        """Save chain state to a JSON file.

        Args:
            path: File path to write.

        Returns:
            True on success.
        """
        data = {
            "order": self.order,
            "smoothing": self.smoothing,
            "contexts_seen": self._contexts_seen,
            "transitions": {
                ctx.hex(): dict(counts)
                for ctx, counts in self.transitions.items()
            },
        }
        try:
            with open(path, "w") as f:
                json.dump(data, f, separators=(",", ":"))
            log.info("Markov chain saved: %s (%d contexts)", path, self._contexts_seen)
            return True
        except OSError as e:
            log.warning("Failed to save Markov chain: %s", e)
            return False

    def load(self, path: str) -> bool:
        """Load chain state from a JSON file.

        Args:
            path: File path to read.

        Returns:
            True on success.
        """
        try:
            with open(path) as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            log.debug("Failed to load Markov chain: %s", e)
            return False

        self.order = data.get("order", self.order)
        self.smoothing = data.get("smoothing", self.smoothing)
        self._contexts_seen = data.get("contexts_seen", 0)
        self.transitions = collections.defaultdict(collections.Counter)
        for ctx_hex, counts in data.get("transitions", {}).items():
            ctx = bytes.fromhex(ctx_hex)
            self.transitions[ctx] = collections.Counter({int(k): v for k, v in counts.items()})
        log.info("Markov chain loaded: %s (%d contexts)", path, self._contexts_seen)
        return True
