"""Byte-level Markov chain for fuzz input generation."""

import collections
import random


class MarkovChain:
    """Byte-level Markov chain for fuzz input generation.

    Learns byte-level transition probabilities from training data and
    generates new inputs that follow the learned statistical patterns.

    Args:
        order: Number of previous bytes to use as context (n-gram order).
        smoothing: Laplace smoothing factor to avoid zero probabilities.

    Examples:
        >>> mc = MarkovChain(order=1)
        >>> mc.train(b"HTTP")
        >>> mc.is_trained()
        True
        >>> sample = mc.generate(4)
        >>> len(sample)
        4
    """

    def __init__(self, order: int = 1, smoothing: float = 1e-6):
        self.order = order
        self.smoothing = smoothing
        self.transitions: dict[bytes, collections.Counter] = collections.defaultdict(
            collections.Counter
        )
        self._contexts_seen = 0

    def train(self, data: bytes) -> None:
        """Learn byte transitions from a single input.

        Args:
            data: Raw bytes to train on.
        """
        for i in range(len(data)):
            ctx = bytes(data[max(0, i - self.order) : i]) if self.order else b""
            self.transitions[ctx][data[i]] += 1
            self._contexts_seen += 1

    def train_corpus(self, corpus: list[bytes]) -> None:
        """Train on multiple inputs.

        Args:
            corpus: List of byte sequences to train on.
        """
        for data in corpus:
            self.train(data)

    def generate(self, length: int) -> bytes:
        """Generate a new input of specified length from learned distribution.

        Args:
            length: Number of bytes to generate.

        Returns:
            Generated byte sequence.
        """
        result = bytearray()
        ctx = b"\x00" * self.order
        for _ in range(length):
            counts = self.transitions.get(ctx)
            if counts is None or not counts:
                result.append(random.randint(0, 255))
                ctx = bytes(result[max(0, len(result) - self.order) :])
                continue
            total = sum(counts.values()) + self.smoothing * 256
            r = random.random() * total
            cumulative = 0.0
            for byte_val, count in counts.items():
                cumulative += count + self.smoothing
                if r <= cumulative:
                    result.append(byte_val)
                    break
            else:
                result.append(random.randint(0, 255))
            ctx = bytes(result[max(0, len(result) - self.order) :])
        return bytes(result)

    def sample_byte(self, ctx: bytes) -> int:
        """Sample a single byte given a context window.

        Args:
            ctx: Context bytes (length should match order).

        Returns:
            Sampled byte value (0-255).
        """
        counts = self.transitions.get(ctx)
        if counts is None or not counts:
            return random.randint(0, 255)
        total = sum(counts.values()) + self.smoothing * 256
        r = random.random() * total
        cumulative = 0.0
        for byte_val, count in counts.items():
            cumulative += count + self.smoothing
            if r <= cumulative:
                return byte_val
        return random.randint(0, 255)

    def is_trained(self) -> bool:
        """Check if the chain has learned any transitions.

        Returns:
            True if any training data has been observed.
        """
        return self._contexts_seen > 0
