"""Monte Carlo scheduler: Thompson sampling bandit + CEM byte distribution."""

import random


class MonteCarloScheduler:
    """Thompson sampling bandit for mutation ops + CEM byte distribution.

    Combines two Monte Carlo methods:
    1. Thompson sampling to select which mutation operator to use
    2. Cross-entropy method to learn per-position byte distributions

    Args:
        elite_frac: Fraction of elite set to use when fitting CEM distribution.
        refit_interval: How often (in executions) to refit the CEM distribution.

    Examples:
        >>> mc = MonteCarloScheduler()
        >>> mc.init_arm("bit_flip")
        >>> mc.init_arm("byte_flip")
        >>> op = mc.select_op(["bit_flip", "byte_flip"])
        >>> mc.record(op, success=True)
    """

    ELITE_MAX = 200

    def __init__(self, elite_frac: float = 0.1, refit_interval: int = 1000):
        self.arm_alpha: dict[str, float] = {}
        self.arm_beta: dict[str, float] = {}
        self.elite_frac = elite_frac
        self.refit_interval = refit_interval
        self.execs_since_refit = 0
        self.elite_set: list[tuple[int, bytes]] = []
        self.byte_freq: dict[int, dict[int, int]] = {}
        self.cem_fitted = False

    def init_arm(self, name: str) -> None:
        """Register a mutation operator arm with prior (1, 1).

        Args:
            name: Name of the mutation operator.
        """
        if name not in self.arm_alpha:
            self.arm_alpha[name] = 1.0
            self.arm_beta[name] = 1.0

    def select_op(self, ops: list[str]) -> str:
        """Select mutation operator via Thompson sampling.

        Args:
            ops: Available mutation operators.

        Returns:
            Name of the selected operator.
        """
        best_op = ops[0]
        best_val = -1.0
        for op in ops:
            a = self.arm_alpha.get(op, 1.0)
            b = self.arm_beta.get(op, 1.0)
            val = random.betavariate(a, b)
            if val > best_val:
                best_val = val
                best_op = op
        return best_op

    def record(self, name: str, success: bool) -> None:
        """Record outcome for a mutation operator arm.

        Args:
            name: Name of the mutation operator.
            success: Whether the mutation produced an interesting result.
        """
        if success:
            self.arm_alpha[name] = self.arm_alpha.get(name, 1.0) + 1
        else:
            self.arm_beta[name] = self.arm_beta.get(name, 1.0) + 1

    def add_elite(self, data: bytes, score: int) -> None:
        """Add an input to the elite set for CEM fitting.

        Args:
            data: The input bytes.
            score: Quality score (higher is better).
        """
        self.elite_set.append((score, data))
        if len(self.elite_set) > self.ELITE_MAX:
            self.elite_set.sort(key=lambda x: x[0])
            self.elite_set.pop(0)

    def maybe_refit(self) -> None:
        """Refit the CEM byte distribution if interval has been reached."""
        if self.execs_since_refit < self.refit_interval:
            return
        self.execs_since_refit = 0
        if not self.elite_set:
            return
        n_elite = max(1, int(len(self.elite_set) * self.elite_frac))
        sorted_elite = sorted(self.elite_set, key=lambda x: x[0], reverse=True)
        elite = [d for _, d in sorted_elite[:n_elite]]
        self.byte_freq = {}
        for pos in range(max(len(d) for d in elite)):
            freq: dict[int, int] = {}
            for data in elite:
                if pos < len(data):
                    b = data[pos]
                    freq[b] = freq.get(b, 0) + 1
            self.byte_freq[pos] = freq
        self.cem_fitted = True

    def cem_byte(self, pos: int) -> int:
        """Sample a byte at a given position from the CEM distribution.

        Args:
            pos: Byte position in the input.

        Returns:
            Sampled byte value (0-255).
        """
        freq = self.byte_freq.get(pos)
        if not freq:
            return random.randint(0, 255)
        total = sum(freq.values()) + 256
        r = random.random() * total
        cumulative = 0
        for byte_val, count in freq.items():
            cumulative += count + 1
            if r <= cumulative:
                return byte_val
        return random.randint(0, 255)

    def cem_sample(self, length: int) -> bytes:
        """Generate a full input from the CEM distribution.

        Args:
            length: Number of bytes to generate.

        Returns:
            Generated byte sequence.
        """
        return bytes(self.cem_byte(i) for i in range(length))

    def bandit_stats(self) -> dict[str, tuple[float, float]]:
        """Get success/failure counts for each arm.

        Returns:
            Dict mapping operator name to (successes, failures).
        """
        result = {}
        for name in sorted(self.arm_alpha):
            a = self.arm_alpha[name]
            b = self.arm_beta[name]
            result[name] = (a - 1, b - 1)
        return result
