#!/usr/bin/env python3
"""Generate a synthetic fuzz target with a controllable edge count.

Three long-standing gaps in the target matrix, all of which this closes:

1. **Nothing exercises the coverage map cap except `ffmpeg_read`.** Every
   other target sizes to the 8192-entry floor at ~13% load, so anything
   that only bites at high load -- probe cost, drop rate, map sizing --
   could be argued about but not measured without a heavy vendor build.
   `--blocks` sets the guard count directly.

2. **No target has a genuinely coverage-dead byte region.** Four real
   campaigns (zlib, png twice, jpeg) failed to produce one, and two of
   those failures are structural rather than accidental: compressed data
   has no padding, and any CRC-covered format rules out dead bytes
   outright, since mutating any byte moves the CRC-check edge regardless of
   semantic relevance. That left `LiveBitMaskEstimator`'s false-negative
   rate unmeasurable -- see handover Sequencing step 6. This target has a
   region that is read but provably never reaches a branch, and no checksum
   anywhere.

3. **No target has known-nondeterministic edges.** Seed stability
   calibration had to be validated against fakes. `--unstable N` emits
   blocks gated on ASLR, so the ground truth is known by construction.

The point of all three is that ground truth is known *by construction*
rather than inferred from the target's behaviour, which is what makes a
false-negative rate measurable at all.

Usage:
    python tools/gen_synthetic_target.py --blocks 20000 -o targets/synthetic_cov.c

Build (clang instruments the blocks naturally):
    clang -O1 -fsanitize-coverage=trace-pc-guard -shared -fPIC \\
        -o targets/synthetic_cov.so targets/synthetic_cov.c

Build without clang -- gcc cannot do trace-pc-guard, so the blocks call the
guard callback themselves. Same code path in the shim either way:
    gcc -O1 -DSYNTH_MANUAL_GUARDS -shared -fPIC \\
        -o targets/synthetic_cov.so targets/synthetic_cov.c

Keep -O1 or lower: at -O2 the block bodies are dead-store-eliminated and
merged, and the guard count collapses.
"""

from __future__ import annotations

import argparse
import sys

HEADER = r'''/* GENERATED by tools/gen_synthetic_target.py -- do not edit by hand.
 *
 * Synthetic coverage target with known ground truth.
 *
 * Input layout:
 *   [0 .. LIVE_LEN)              live region   -- selects which blocks run
 *   [LIVE_LEN .. LIVE_LEN+DEAD_LEN)  DEAD region -- read, never branched on
 *   [LIVE_LEN+DEAD_LEN .. )      live tail     -- selects unstable blocks
 *
 * The dead region is the point of this file. Its bytes are summed into
 * `dead_acc`, which is written to a volatile sink and never compared,
 * tested, or used as an index. No control-flow edge anywhere in this
 * translation unit depends on any byte in that range, so mutations landing
 * there produce a coverage diff of exactly zero -- by construction, not by
 * observation. There is no checksum over any part of the input, which is
 * what every real format in the matrix failed to provide.
 *
 * `volatile` on the sink is load-bearing: without it the compiler proves
 * dead_acc is unused and deletes the reads, and then the region is dead for
 * an uninteresting reason (nothing touches it) rather than the interesting
 * one (it is touched but never decides anything).
 */
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

#define LIVE_LEN %(live_len)d
#define DEAD_LEN %(dead_len)d
#define N_BLOCKS %(n_blocks)d

/* Byte offsets of the dead region, exported so tests and sweeps can assert
   against ground truth instead of rediscovering it. */
__attribute__((visibility("default"))) const int synth_dead_start = LIVE_LEN;
__attribute__((visibility("default"))) const int synth_dead_len   = DEAD_LEN;
__attribute__((visibility("default"))) const int synth_n_blocks   = N_BLOCKS;

static volatile uint64_t sink;

#ifdef SYNTH_MANUAL_GUARDS
/* gcc has no -fsanitize-coverage=trace-pc-guard. Call the shim's callback
   directly so the generated blocks still produce edges: this is the same
   entry point clang's instrumentation targets, so the shim sees no
   difference. One guard word per block, matching clang's layout. */
extern void __sanitizer_cov_trace_pc_guard(uint32_t *guard);
extern void __sanitizer_cov_trace_pc_guard_init(uint32_t *start, uint32_t *stop);
static uint32_t synth_guards[N_BLOCKS + 1];

/* clang emits this call itself; the manual path has to make it. Without it
   every guard word stays 0 and the shim's callback returns immediately
   (`if (!guard || *guard == 0) return;`), so the target produces no edges
   at all and every measurement built on it silently reads zero. */
__attribute__((constructor))
static void synth_guard_init(void) {
    __sanitizer_cov_trace_pc_guard_init(synth_guards, synth_guards + N_BLOCKS + 1);
}
#define BLOCK_MARK(i) __sanitizer_cov_trace_pc_guard(&synth_guards[i])
#else
#define BLOCK_MARK(i) do { } while (0)
#endif

__attribute__((visibility("default")))
int fuzz_synthetic(const unsigned char *buf, size_t n) {
    uint64_t acc = 0;
    uint64_t dead_acc = 0;

    if (n < 2) return 0;

    /* ---- DEAD REGION: read, accumulated, never branched on ---- */
    for (size_t i = LIVE_LEN; i < n && i < (size_t)(LIVE_LEN + DEAD_LEN); i++)
        dead_acc += buf[i];
    sink = dead_acc;   /* consumed, so the reads are real; never tested */

    /* ---- LIVE REGION: selects which of N_BLOCKS blocks execute ---- */
    uint32_t sel = 0;
    for (size_t i = 0; i < n && i < LIVE_LEN; i++)
        sel = sel * 31u + buf[i];

'''

FOOTER = r'''
    sink = acc;
    return 0;
}
'''

UNSTABLE = r'''
    /* ---- UNSTABLE BLOCKS: gated on ASLR, nondeterministic by design ----
       The address of a heap allocation varies run to run under ASLR, so
       these edges fire on some executions of an identical input and not
       others -- exactly the case seed stability calibration exists to mask.
       Gated on a live-region byte too, so they are reachable only for some
       inputs rather than firing unconditionally. */
    if (n > LIVE_LEN + DEAD_LEN) {
        void *p = malloc(1);
        uintptr_t a = (uintptr_t)p;
        free(p);
        uint32_t tail = buf[n - 1];
'''


def gen_blocks(n_blocks: int, fanout: int) -> str:
    """Emit a switch over `sel` with one case per block.

    A switch rather than a chain of ifs: clang lowers a dense switch to a
    jump table, so each case is its own basic block and gets its own guard,
    which keeps the guard count close to --blocks. A nested if-chain would
    make every block's reachability depend on all the ones before it, so a
    single input could only ever reach a handful.
    """
    out = [f"    switch (sel % {n_blocks}) {{"]
    for i in range(n_blocks):
        out.append(f"    case {i}: acc += {i * 2654435761 & 0xFFFFFFFF}u; BLOCK_MARK({i}); break;")
    out.append("    default: break;")
    out.append("    }")

    # A second, independent selector so one execution reaches several
    # blocks. Without it every input produces exactly one edge and the map
    # never fills no matter how many blocks the binary contains.
    #
    # Under SYNTH_MANUAL_GUARDS this marks guard[s2] directly, which gives
    # exactly --fanout distinct edges per execution. Under clang the loop
    # body is one basic block, so it contributes ~1 guard rather than
    # n_blocks: clang gets its guard count from the switch above, which is
    # what map sizing keys on, while per-execution edge count is lower.
    # Stated plainly because a measurement that assumes both are high under
    # clang would be wrong.
    out.append("")
    out.append(f"    for (int r = 1; r < {max(2, fanout)}; r++) {{")
    out.append(f"        uint32_t s2 = (sel * 2654435761u + r * 40503u) % {n_blocks};")
    out.append("#ifdef SYNTH_MANUAL_GUARDS")
    out.append("        BLOCK_MARK(s2);")
    out.append("#else")
    out.append("        if (s2 & 1u) acc += s2; else acc ^= s2;")
    out.append("#endif")
    out.append("    }")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--blocks", type=int, default=20000, help="number of distinct blocks/guards")
    ap.add_argument("--fanout", type=int, default=8, help="blocks reached per execution")
    ap.add_argument("--live-len", type=int, default=32, help="live prefix length in bytes")
    ap.add_argument("--dead-len", type=int, default=64, help="dead region length in bytes")
    ap.add_argument("--unstable", type=int, default=4, help="ASLR-gated unstable blocks")
    ap.add_argument("-o", "--out", default="targets/synthetic_cov.c")
    args = ap.parse_args()

    if args.blocks < 2:
        print("--blocks must be >= 2", file=sys.stderr)
        return 2

    src = HEADER % {
        "live_len": args.live_len,
        "dead_len": args.dead_len,
        "n_blocks": args.blocks,
    }
    src += gen_blocks(args.blocks, args.fanout)

    if args.unstable > 0:
        src += UNSTABLE
        for u in range(args.unstable):
            gid = args.blocks - 1 - u
            src += (
                f"        if (((a >> {12 + u}) & 1u) && (tail & {1 << u}u))"
                f" {{ acc += {u}u; BLOCK_MARK({gid}); }}\n"
            )
        src += "    }\n"

    src += FOOTER

    with open(args.out, "w") as fh:
        fh.write(src)
    print(f"wrote {args.out}: {args.blocks} blocks, dead region [{args.live_len}, "
          f"{args.live_len + args.dead_len}), {args.unstable} unstable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
