#!/usr/bin/env python3
"""Generate the AFLGo distance table for a target.

Computes the PC→distance table (trace-pc call sites of valued blocks,
keys relative to the object base) for a fuzz target and either prints it
or emits a C source file with the table.  At runtime the fuzzer uploads
the same table to shared memory (__AFL_DIST_SHM_ID); this tool exists
for inspection, debugging, and build-time integration.

Usage:
  gen_distance_table.py TARGET OUT.c [targets...]
  gen_distance_table.py TARGET - [targets...]   # print table to stdout
"""

import argparse
import sys


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", help="Path to the ELF binary")
    parser.add_argument("out", help="Output C file ('-' for stdout)")
    parser.add_argument("targets", nargs="*", default=None, help="Target function(s)/file.c:line")
    args = parser.parse_args()

    from fuzzer_tool.core.distance import TargetDistance

    td = TargetDistance(args.target, args.targets)
    if not td.load():
        print(f"error: TargetDistance failed to load {args.target}", file=sys.stderr)
        return 1
    table = td.pc_distance_table()
    if not table:
        print(
            f"error: no distance table for {args.target} "
            "(is it built with -D__AFL_DISTANCE_MODE -fsanitize-coverage=trace-pc?)",
            file=sys.stderr,
        )
        return 1

    if args.out == "-":
        for key in sorted(table):
            print(f"0x{key:x} {table[key]:.2f}")
        return 0

    with open(args.out, "w") as f:
        f.write("/* Generated by gen_distance_table.py — do not edit. */\n")
        f.write("#include <stdint.h>\n\n")
        f.write("struct __afl_dist_entry { uint64_t key; uint32_t dist; };\n\n")
        f.write("const struct __afl_dist_entry __afl_distance_table[] = {\n")
        for key in sorted(table):
            f.write(f"    {{ 0x{key:x}ULL, {max(0, round(table[key] * 100))} }},\n")
        f.write("};\n")
        f.write(f"const uint32_t __afl_distance_table_size = {len(table)};\n")
    print(f"wrote {len(table)} entries to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
